### ISSUE TITLE
Buyweapon

### ISSUE THREAD

**Issue by SkippYSB** [Bara20/TroubleinTerroristTown#103]
Buyweapon buying 2 M4's, dropping 1 on the ground.

**Comment by good-live** [comment]
Is this a issue or a bug? Try again please.

**Comment by SkippYSB** [comment]
More like a bug? Should it give one and drop one?

**Comment by good-live** [comment]
You should describe what you are expecting it to do and what it's actually does.

**Comment by SkippYSB** [comment]
I'm expecting it to buy 1 m4 for the player who buys it. I'm not expecting it to buy 1 and drop 1 on the ground.

**Comment by good-live** [comment]
It only drops the primary weapon that the player already has and gives him a new m4. Maybe you have 2 versions on your server?

**Comment by SkippYSB** [comment]
Okay, i will look more into this. Thank you.
