### ISSUE TITLE
Blue Body Tint

### ISSUE THREAD

**Issue by popey456963** [Bara20/TroubleinTerroristTown#105]
Just upgraded our server version, started seeing the following:

![](https://puu.sh/wlSkz/a88bdc4e4b.png)

However we also updated CS:GO at the same time, wondering whether any other servers have started seeing this and whether they know the cause?  

It seems to always be one person per map, and is consistent during the round.

**Comment by Bara20** [comment]
Player respawned?

**Comment by popey456963** [comment]
@Bara20 We have that ability disabled, (I think maybe TTT disables the command itself even?), so I don't see how he could have been respawned.

Also, same person across rounds, definitely doesn't seem to be being respawned that many times.

**Comment by popey456963** [comment]
We use it, however this person is not frozen and people don't appear to be blue tinted when they are frozen with the ice knife.

**Comment by good-live** [comment]
Can you disable it and see if the bug still appears?

**Comment by popey456963** [comment]
@good-live Spent some more time on it this morning, woke up early so no-one on the server :)

Disabling the ice knife plugin does indeed seem to stop the blue tint bug from happening.  That doesn't explain why this would suddenly start happening when I upgraded though, because I checked through the code and couldn't see any alterations to that plugin recently.

I did note another person had created a `reload-ttt.cfg` file and was executing it at the start of every map.  This appears to fix several issues, such as the lack of a red borders around traitor allies but introduces more bugs like the ice knife blue tint.  It does the following:

```
say "reloading TTT plugins"
//custom plugins
sm plugins reload ttt-ninja.smx

//ttt plugins
sm plugins reload ttt/ttt_shop.smx
sm plugins reload ttt/ttt_weaponitems.smx
sm plugins reload ttt/ttt_wallhack.smx
sm plugins reload ttt/ttt_traitordoors.smx
sm plugins reload ttt/ttt_taser.smx
sm plugins reload ttt/ttt_talk_override.smx
sm plugins reload ttt/ttt_tagrenade.smx
sm plugins reload ttt/ttt_stations.smx
sm plugins reload ttt/ttt_sql.smx
sm plugins reload ttt/ttt_spec_menu.smx
sm plugins reload ttt/ttt_player_hud.smx
sm plugins reload ttt/ttt_overlay.smx
sm plugins reload ttt/ttt_id.smx
sm plugins reload ttt/ttt_icon.smx
sm plugins reload ttt/ttt_iceknife.smx
sm plugins reload ttt/ttt_hide_radar.smx
sm plugins reload ttt/ttt_healthshot.smx
sm plugins reload ttt/ttt_grabbermod.smx
sm plugins reload ttt/ttt_glow.smx
sm plugins reload ttt/ttt_fakebody.smx
sm plugins reload ttt/ttt_dnascanner.smx
sm plugins reload ttt/ttt_decoy_teleport.smx
sm plugins reload ttt/ttt_crashcatcher.smx
sm plugins reload ttt/ttt_c4_jihad.smx
say "reloading TTT plugins done"
```

Disabling this also meant that the blue tint bug wouldn't happen, even when the ice knife plugin was enabled.  (Interestingly, this also appears to cause red/blue/green borders around everyone when used in the middle of a round, so it should only be run when TTT is off).

Is there a safer way to reload TTT which doesn't cause these issues?

**Comment by rautamiekka** [comment]
^ Try updating TTT first, there's been at least 1 release during this time.

**Comment by Bara20** [comment]
Could you reproduce this with the latest version?

**Comment by popey456963** [comment]
I could not, apologies for not using the latest version :)
