### ISSUE TITLE
VPhysics.so Crash on Latest Version of TTT

### ISSUE THREAD

**Issue by popey456963** [Bara20/TroubleinTerroristTown#106]
Recently upgraded to the latest version of TTT, since doing so the server is crashing intermittently (once or twice a day) when there are ~30 people online.

Only appears to crash on high player numbers, with the reason being "vphysics.co".  You can see the crash log [here](https://crash.limetech.org/gmktzrwcgjrq).

**Comment by 4bdul** [comment]
Which version was you running previously?

**Comment by popey456963** [comment]
It was probably ~ a year old.  I stepped away from my server for ages and the new owner didn't upgrade it.  Someone pointed out I don't actually have the latest version at the moment, I must have grabbed the wrong one.  Give me a few days to upgrade it (have to wait till no-ones playing) to check I'm not just talking about an older version.

**Comment by Bara20** [comment]
Any updates @popey456963 ?

**Comment by popey456963** [comment]
Not crashing on the latest version!  But then again we also haven't hit >25 players.

Considering I can't reproduce at the moment, will close the issue!
