### ISSUE TITLE
Body ID won't work when reconnecting

### ISSUE THREAD

**Issue by 4bdul** [Bara20/TroubleinTerroristTown#110]
Scenario: Player dies, and reconnects to the server before their ragoll is ID'd.

In such scenario's, when you ID the body, it will show the menu, but it **won't** color the ragoll and it **won't** print in chat that you identified the body.

If a player was to disconnect, and not come back, their body can be ID'd just fine.

**Comment by good-live** [comment]
The problem is that it's not possible to determine the victims team when he's offline.
To support this correctly the team needs to be saved with the ragdoll.

I'll take a look at it.

**Comment by good-live** [comment]
Can you test it with the newest version?

**Comment by 4bdul** [comment]
I've tested this and works fine. Thanks for that!
