### ISSUE TITLE
VIP Features

### ISSUE THREAD

**Issue by Bara20** [Bara20/TroubleinTerroristTown#113]
https://forums.alliedmods.net/showpost.php?p=2531391&postcount=554
https://forums.alliedmods.net/showpost.php?p=2531424&postcount=556

**Comment by 4bdul** [comment]
Perhaps just apply a shop % discount for traitors; and maybe a better % chance of becoming traitor?

**Comment by Bara20** [comment]
@4bdul You could buy instantly (or next round) roles as innocent.
