### ISSUE TITLE
!detective

### ISSUE THREAD

**Issue by Jezis** [Bara20/TroubleinTerroristTown#115]
simple menu appears when you write this, so you can choose to be detective or not again

**Comment by Bara20** [comment]
You could [buy the roles](https://github.com/Bara20/TroubleinTerroristTown/blob/master/addons/sourcemod/scripting/ttt/ttt_buyRoles.sp) (next round + instant)

To avoid [this role](https://github.com/Bara20/TroubleinTerroristTown/blob/master/addons/sourcemod/scripting/ttt/ttt.sp#L241) you can set this cvar to true

**Comment by Jezis** [comment]
You can close this. Ive found that you can use simply !drules. Thats the command i was looking for :)
