### ISSUE TITLE
!setrole broken

### ISSUE THREAD

**Issue by omar-damaj** [Bara20/TroubleinTerroristTown#116]
Using version 1017 breaks !setrole for some reason. 
!setrole playername 2 works fine but !setrole 1 or 2 is broken

The version that is on the downloads site has weird symbols as well in the translations text file. Easy fix but wanted to bring it up. 

	"Player is Now Innocent"
	{
		"#format"	"{1:N}"
		"en"		"{orchid}{1} {lightgreen}ç¾åœ¨æ˜¯ {green}å¹³æ°‘!"
	}

**Comment by good-live** [comment]
The translation should be fixed now.

The other one occurs, because i've changed the Team indexes a few commits before.
I'll fix this asap.
