### ISSUE TITLE
Kevlar/KevHelm/Heavy items are not shown in shop menu

### ISSUE THREAD

**Issue by 4bdul** [Bara20/TroubleinTerroristTown#123]
Traitors, Detectives, and Innocents cannot see the items that are for team "1" in their shop menu - it is supposed to show it to everyone. (khelm, kevlar, helm, heavy).

sm_showitems
ShortName - LongName, Team
khelm - Kevlar+Helm, 1
fb - Fakebody, 4
hlthstat - Health Station, 8
taser_t - Taser, 4
taser_d - Taser, 8
heavy - Heavy, 1
taser - Taser, 2
c4 - C4, 4
wh_d - Wallhack, 8
jihad - Jihad Bomb, 4
wh_t - Wallhack, 4
usps - USP-S, 4
hurtstat - Death Station, 4
hs_t - Healthshot, 4
hs - Healthshot, 2
1knife - 1-Hit Knife, 4
m4a1s - M4A1-S, 4
hs_d - Healthshot, 8
awp - AWP, 4
dna - DNA Scanner, 8
helm - Helm, 1
kevlar - Kevlar, 1

**Comment by Bara20** [comment]
Try this

**Comment by 4bdul** [comment]
Works, thanks!
