### ISSUE TITLE
Role issue

### ISSUE THREAD

**Issue by Bobakanoosh** [Bara20/TroubleinTerroristTown#129]
I updated to the most recent commit on SM 1.8. Several plugins that i've made with ttt inc's are bugging out, all revolving around roles.

```
int role = TTT_GetClientRole(target);
	
CPrintToChat(client, "%N: %i", target, role);
CPrintToChat(client, "%i %i %i", TTT_TEAM_TRAITOR, TTT_TEAM_DETECTIVE, TTT_TEAM_INNOCENT);
```

After putting this in a command, i get this output while traitor:

```
Bobakanoosh: 4
2 3 1
```

I get a 2 while innocent, and an 8 when detective.

**Comment by good-live** [comment]
Youll need to recompile your plugin with the latest include. I've changed the indices.

**Comment by Bobakanoosh** [comment]
That's fixed that issue good-live, but after doing so I'm having another issue where innocents can buy several traitor items like decoy teleporters, fake bodies, ak's, etc. Is this related at all or do you have any idea? Am just on the most recent commit for SM 1.8.

I do have modified versions of fake bodies / teleporters but I recompiled them with the new includes, and that doesn't explain them being able to buy some t guns either. Nothing's changed in configs either to my knowledge.

**Comment by good-live** [comment]
Is your shop also compiled with the latest include?
Can innocents buy all custom items or only some?

**Comment by Bobakanoosh** [comment]
I downloaded the .smx's you guys provided with the latest commit, and then replaced the modules that I eddited (Decoy teleporter and fake body).

http://i.imgur.com/cafH8hi.png

Those are the items you can buy as innocent, including fake body.  There's some missing compared to when you're a traitor like wall hack.

**Comment by good-live** [comment]
Have you restarted your server already?

**Comment by Bobakanoosh** [comment]
Not at all yet, usually crashes semi-frequently so I had assumed it had. Quite a few people on at the moment so I'll wait for it to die down, restart, and then I'll get back to you.

**Comment by Bobakanoosh** [comment]
Fixed it :I now I feel a little dumb lmao. Thanks for your help.
