### ISSUE TITLE
Compatibility with Cameras and Drones

### ISSUE THREAD

**Issue by Keplyx** [Bara20/TroubleinTerroristTown#130]
Hi, as you know, some people requested my plugin [Cameras and drones](https://forums.alliedmods.net/showthread.php?t=299696) to be available in the TTT shop.

You asked me to make a buy native, so I made it along with a native to override the gear (camera/drone) available for a player. That way you could for example set the gear to drone for everyone except the detective, make that only the traitors can buy the drones and only the detectives can buy the camera.

The modifications are available in the [dev branch](https://github.com/Keplyx/cameras-and-drones/tree/dev), as I'm not sure if they fully work (first time making natives).

If you need anything in my plugin to be changed in order to make it work with yours, tell me!

**Comment by Bara20** [comment]
Thanks for the native @Keplyx , I'll add this later today.

**Comment by Bara20** [comment]
I've added cameras for detectives and drones for traitors.
