### ISSUE TITLE
TTT_OnRoundStart_Pre Bug/Inaccurate Description

### ISSUE THREAD

**Issue by lay295** [Bara20/TroubleinTerroristTown#132]
Hello, I was trying to make a !slaynr plugin for my community, and came across the TTT_OnRoundStart_Pre forward which has this description "Called before players roles are picked/assigned ... You could slay players here to force them to sit out" so I thought perfect, and make a plugin to slay them on that forward, however it respawns them still. I can kill them at TTT_OnRoundStart however that messes with team balance.

I have fixed it on my version of TTT, but would like for it to be fixed here as I'm sure I wouldn't be the only one with this issue. The forward is called on ttt/ttt.sp on line #784 and the respawn is at #810

I would make a pull request but have never used github before, either way it should be a simple fix.

**Comment by good-live** [comment]
Could you quickly test this with the latest version?
I have no chance to test it here.

Close the issue please if your problem is solved.

**Comment by lay295** [comment]
This has fixed the issue, thanks
