### ISSUE TITLE
Ability to Add Health Station to Detectives

### ISSUE THREAD

**Issue by omar-damaj** [Bara20/TroubleinTerroristTown#134]
Is there a possible way that the detectives can have the health station added to their store?

**Comment by good-live** [comment]
Its already a detective item.

**Comment by omar-damaj** [comment]
Oh I see it in game! I guess I was confused because the config file said it was for traitors only. 
Probably just an outdated config file. Thanks for letting me know!
"health_station_price"
	{
		"value"		"2000"
		"description"		"The price of the Health Station in the shop for traitors. 0 to disable."
	}
