### ISSUE TITLE
Issue With Buying Drones/Cameras

### ISSUE THREAD

**Issue by omar-damaj** [Bara20/TroubleinTerroristTown#135]
I have enabled drones on the server as well as updated TTT to the newest version. 
When I buy drones all it says is the following: 
 [eGO TTT] Item Drone bought for 9000 credits! Remaining Credits: 7991297
Nothing in inventory though. 

Same thing with Cameras for detectives.

**Comment by whocodes** [comment]
I would consider this to be a problem with the drones plugin (which is not a plugin included in this repository).

**Comment by omar-damaj** [comment]
The drone plugin works from what I saw. I used cd_buy and it worked there but it was not attached to TTT.

**Comment by Bara20** [comment]
You'll get now a tagrenade for Cameras/Drones ( https://github.com/Bara20/TroubleinTerroristTown/commit/83d155496ae2b70194158546ce422de5134700c0 ).

Throw it and type "!cd_cam" in chat or "cd_cam" in console ( https://github.com/Keplyx/cameras-and-drones/tree/dev#commands ).

**Comment by Bara20** [comment]
If you've problems then reopen this issue.
