### ISSUE TITLE
Ranking players

### ISSUE THREAD

**Issue by Jezis** [Bara20/TroubleinTerroristTown#139]
Is it possible to add a mysql table, that will store how many players everyone kill as an innocent and as an traitor? 
And after !rank, it will show you how good are you.

**Comment by whocodes** [comment]
#22


On Aug 14, 2017, at 6:12 AM, Jezis <notifications@github.com<mailto:notifications@github.com>> wrote:


Is it possible to add a mysql table, that will store how many players everyone kill as an innocent and as an traitor?
And after !rank, it will show you how good are you.
