### ISSUE TITLE
C4 Wallhack for T's

### ISSUE THREAD

**Issue by kikoplg** [Bara20/TroubleinTerroristTown#14]
There is no more outline (C4 Glow) of c4 to traitor team. This is a huge problem for the strategic traitors in this gamemode!

**Comment by kikoplg** [comment]
Sollte so schnell wie möglich gemacht werden, GAMEBREAKING!!!

**Comment by Bara20** [comment]
Naja "Gamebreaking" nicht gerade, eher dummer Zufall wenn ein anderer T dabei stirbt. ;)

**Comment by good-live** [comment]
War ja früher mal drin. Ich hab das bein über nehmen in ein eigenes Plugin weggelassen, weil der Kringel nicht sehr schön aussah :D. Zur not kann man ja den alten code über nehmen. Ansonsten mach ich bei Zeiten mal eine schönere Lösung. Aber gamebreaking ist das tatsächlich nicht ^^

**Comment by Bara20** [comment]
@good-live Man könnte den Glow Effekt wie beim TA-Grenade (beim Spieler) Feature schreiben.
Die netprops wie prop_physics sind (fast) die selben wie bei einen Spieler ( http://pastebin.com/pVDzmRpY ).

**Comment by good-live** [comment]
Ich schau es mir heute Abend mal an.

**Comment by kikoplg** [comment]
Man könnte den Glow Effekt wie bei der TA-Grenade nehmen.

**Comment by Bara20** [comment]
@kikoplg soweit ich es damals getestet habe, ging m_clrRender nicht für solche props.

**Comment by kikoplg** [comment]
Dann spawnen wir ein Prop bei dem es geht in die Bombe rein und glowen das. Sollte doch funktionieren ?

**Comment by kikoplg** [comment]
Probier mal "props/coop_cementplant/grenade_box/grenade_box_closed.mdl" und scale es ein wenig runter.
