### ISSUE TITLE
Shows innos as dead in tab when killed

### ISSUE THREAD

**Issue by grinchhh** [Bara20/TroubleinTerroristTown#140]
It is showing inno's as killed without id'ing the bodies.

The only error I am getting atm is this:
L 08/14/2017 - 12:11:39: Info (map "ttt_tumbleweed_v1_3") (file "errors_20170814.log")
L 08/14/2017 - 12:11:39: [SM] Exception reported: Entity -1 is invalid
L 08/14/2017 - 12:11:39: [SM] Blaming: TTT\ttt.smx
L 08/14/2017 - 12:11:39: [SM] Call stack trace:
L 08/14/2017 - 12:11:39: [SM]   [0] SDKHook
L 08/14/2017 - 12:11:39: [SM]   [1] Line 635, addons/sourcemod/scripting/ttt/ttt.sp::OnMapStart
L 08/14/2017 - 12:12:05: [GFL\GFL-Core.smx] [GFL-Core]Failed to log message. Cannot open/read/write file.

**Comment by Bara20** [comment]
[Fixed](https://github.com/Bara20/TroubleinTerroristTown/commit/b74ed5ae8d26b8428780748afac8a2db34252165)
