### ISSUE TITLE
TA-Grenade and Camera and Drones

### ISSUE THREAD

**Issue by Bara20** [Bara20/TroubleinTerroristTown#142]
TA-Grenade doesn't work with Cameras and Drones. @Keplyx TAGrenade doesn't explode.

https://github.com/Keplyx/cameras-and-drones/blob/dev/scripting/cameras-and-drones.sp#L294
You've no check if the player has a bought or override gear.

**Comment by Keplyx** [comment]
I didn't make the plugin thinking people would use tagrenades, but I'm going to fix this. I'll tell you when the update is ready!

**Comment by Keplyx** [comment]
Updated the [plugin](https://github.com/Keplyx/cameras-and-drones/tree/master). You should now be able to use cameras/drones when you bought one, and TA-Grenades when you haven't. Set "cd_usetagrenade" to 1 to use this feature. If you have any more problems, tell meI'll try to fix them as soon as possible!

**Comment by Bara20** [comment]
Looks good on my test server. Thanks for updating 👍
