### ISSUE TITLE
Knockout Crashes Server

### ISSUE THREAD

**Issue by PRAWKC** [Bara20/TroubleinTerroristTown#143]
Whenever a T buys Knockout in shop. When they use the knockout taser server crashes.

**Comment by Bara20** [comment]
Could you provide your crash id (generated by [Accelerator](https://forums.alliedmods.net/showthread.php?t=277703))?

**Comment by PRAWKC** [comment]
5KHE-ALKE-C3B2

**Comment by Bara20** [comment]
I've tested it on my jail server with ~20 players and no crash. Try it again with build 1125 (or above)

**Comment by PRAWKC** [comment]
Sorry I forgot an important detail. When you use knockout you must click E on the person you knocked out and move their body around and then the server crashes.

**Comment by Bara20** [comment]
Grabbermod isn't the problem.
