### ISSUE TITLE
Innocent can tell who traitor is by looking

### ISSUE THREAD

**Issue by PRAWKC** [Bara20/TroubleinTerroristTown#144]
Every inno can just look at a player, if the name does not appear in the HUD they are traitor if name appears they are inno.

**Comment by Bara20** [comment]
Any screens?

**Comment by PRAWKC** [comment]
[http://i.imgur.com/IVAQk6z.jpg](url) <-- This is the bug.

**Comment by PRAWKC** [comment]
Not on hand, although this bug happens with everyone. Whoever is inno, just needs to look at a player if no name appears they are T, if a name shows like its supposed to they are inno.

**Comment by Bara20** [comment]
Could you try [build 1120+](https://csgottt.com/) when it's done?

**Comment by PRAWKC** [comment]
Sure, let me know when ready.

**Comment by Bara20** [comment]
Is up.

**Comment by rautamiekka** [comment]
A fairly good way to stay up-to-date with the releases of CS:GO TTT is registering at www.ChangeDetection.com (completely free and hardly any ads; I'm not related) and subscribing to [https://www.changedetection.com/log/csgottt/index_log.html](https://www.changedetection.com/log/csgottt/index_log.html).

ChangeDetection will send you an email daily at maximum (conffable on subscription), assuming the page has changed before the check is done, the emails having gotten to me around 01:41am UTC+2 every time.

**Comment by PRAWKC** [comment]
I tried build 1120 but the bug is still present. Do you have a server I can join with you and test each new build you make?

**Comment by Bara20** [comment]
You can [add me on steam](http://steamcommunity.com/profiles/76561198041923231/), if you want.

**Comment by PRAWKC** [comment]
Added

**Comment by Bara20** [comment]
I can't reproduce this problem.

Traitor-Innocent (looks good):
http://steamcommunity.com/id/bbara/screenshot/868486447400713582
Traitor-Traitor (also):
http://steamcommunity.com/id/bbara/screenshot/868486447400713221
Innocent-Innocent (also):
http://steamcommunity.com/id/bbara/screenshot/868486447400713910
Innocent-Traitor (also):
http://steamcommunity.com/id/bbara/screenshot/868486447400714139

**Comment by PRAWKC** [comment]
@good-live So I have done some testing with SourceMod 1.8.0.6017(Latest Stable Build at this moment. 978 - This Version does not have this bug.
1082 - For Some reason I got karma banned lol idk.
1085 - The bug is present
1090 - The bug is present
1137 - Bug is also on latest Build.

**Comment by good-live** [comment]
Do you use a plugin, that's using the HUD forwards? (Like fakenick)

**Comment by PRAWKC** [comment]
@good-live 
I do not believe I do, but for good measure I removed all custom plugins and kept base sm + TTT plugins that come with build 1085

This is the configuration plus the bug, you can see that he is a traitor and when they are traitor no name appears only karma + health

[http://imgur.com/a/Vn2SQ](http://imgur.com/a/Vn2SQ)

**Comment by Bara20** [comment]
@good-live Karma wird auch als Karma: {2} angezeigt 🤔

**Comment by good-live** [comment]
I'll take a look at it.

**Comment by good-live** [comment]
@PRAWKC are you using the default translation?

**Comment by PRAWKC** [comment]
Yes everything is pretty much Default

**Comment by PRAWKC** [comment]
Okay I think I found something, ill update you in a few.

**Comment by Bara20** [comment]
Makes sense, I've added a check to prevent that for other servers. https://github.com/Bara20/TroubleinTerroristTown/commit/65945d028725051094083b254b491c74e62fbae8
