### ISSUE TITLE
Wallhack

### ISSUE THREAD

**Issue by grinchhh** [Bara20/TroubleinTerroristTown#146]
Wallhack seems to allow detectives to see who is what role from far distances. I cannot locate the error for it, but this is the latest update.

**Comment by Bara20** [comment]
It was [allowed](https://github.com/Bara20/TroubleinTerroristTown/blob/3afa499e70a03e22df56b8679763d58d3761b3b3/addons/sourcemod/scripting/ttt/ttt_wallhack.sp#L82) as detective to buy wallhack.

I've [disabled](https://github.com/Bara20/TroubleinTerroristTown/commit/e33453b7e87ecb08839ea1c92dd57a8f52a37fdc#diff-bb6a7737f5221771c2805ca404cf3e20R82) this now by default.

**Comment by Bara20** [comment]
@grinchhh any updates?

**Comment by grinchhh** [comment]
Working fine now.

**Comment by PRAWKC** [comment]
In build 1192 when you buy wallhack as detective you can still see the roles.

**Comment by Bara20** [comment]
#160
