### ISSUE TITLE
Hurtstation Wallhack for T's

### ISSUE THREAD

**Issue by kikoplg** [Bara20/TroubleinTerroristTown#15]
A couple Ts decided it would be sick to put down Hurt station. Since the hurt station will not effect the person who planted it, it will hurt everyone else, including Ts.
To avoid confusion, why not put the red outline on the hurt station to notify all the traitors, much like the C4 outline?

**Comment by kikoplg** [comment]
Sollte so schnell wie möglich gemacht werden, GAMEBREAKING!!!

**Comment by kikoplg** [comment]
Man könnte den Glow Effekt wie bei der TA-Grenade nehmen.

**Comment by popey456963** [comment]
Hurt stations don't hurt other traitors in the latest release, as far as I know?  Is this still a problem?

**Comment by Bara20** [comment]
You can activate it with hurt_station_hurt_other_traitors

**Comment by Bara20** [comment]
@kikoplg soweit ich es damals getestet habe, ging m_clrRender nicht für solche props.

**Comment by kikoplg** [comment]
Mit der Mikrowelle sollte es gehen. Das es mit C4 nicht geht ist mir bekannt. Aber Mikrowelle sollte funktionieren.

**Comment by kikoplg** [comment]
kk
