### ISSUE TITLE
Futuristic Grenades

### ISSUE THREAD

**Issue by Bara20** [Bara20/TroubleinTerroristTown#152]
https://forums.alliedmods.net/showthread.php?p=2499362
https://pastebin.com/NeWfMbA9

**Comment by KrisTheCanadian** [comment]
I want this so badly.

**Comment by Bara20** [comment]
https://github.com/Bara20/TroubleinTerroristTown/commit/9920d87a7d6ac2b7b160c7b61930907968f65416
