### ISSUE TITLE
Heavy Armor / Armor rolling forward to next round.

### ISSUE THREAD

**Issue by omar-damaj** [Bara20/TroubleinTerroristTown#153]
Would it be possible to set an option to allow for stripping of Heavy Armor or Armor at end of round? That way the players do not keep it for the next round? Seems like that is the case for me at the moment. Players can buy Heavy Armor and keep it for multiple rounds.

**Comment by Bara20** [comment]
Is ttt_transfer_armor 0 ? Or it's just heavy armor?

**Comment by Bara20** [comment]
@omar-damaj ? Otherwise it will be closed with merge of #203
