### ISSUE TITLE
auto slay command?

### ISSUE THREAD

**Issue by grinchhh** [Bara20/TroubleinTerroristTown#155]
Is there any way to add an auto slay command for admins to use for people that are rdming and such? 
Something like /aslay <player> <numberofrounds> <reason>. I know gmod has this feature so.

**Comment by whocodes** [comment]
I wrote a plugin called SlayEx for this exact reason. Needs a little bit of work and may need to he updated for most current TTT version, but it worked when I wrote it perfectly.

Only improvement I can think of is adding it to the !admin menu


You can find the plugin on my GitHub. When TTT was still on git.tf, I planned to implement this into the core plugin somewhere (I don't like when people sell super basic private plugins).

On Aug 22, 2017, at 3:50 AM, grinchhh <notifications@github.com<mailto:notifications@github.com>> wrote:


Is there any way to add an auto slay command for admins to use for people that are rdming and such?
Something like /aslay . I know gmod has this feature so.

**Comment by grinchhh** [comment]
@whocodes I would rather have it hooked into g_fRealRoundStart to be honest. The pre-round just gives the players more of a chance of RDMing after they are slain. I am able to just set it to like 2 and they are slain not once but twice right after another, I rather have it on each real round so they are not able to do rdm sprees and so fourth..

**Comment by whocodes** [comment]
Unless the functionality for TTT changed, that plugin will allow you to slay people for an extended period of rounds (or just the one round)


On Aug 22, 2017, at 1:44 PM, grinchhh <notifications@github.com<mailto:notifications@github.com>> wrote:


@whocodes<https://github.com/whocodes> I would rather have it hooked into g_fRealRoundStart to be honest. The pre-round just gives the players more of a chance of RDMing after they are slain. I am able to just set it to like 2 and they are slain not once but twice right after another, I rather have it on each real round so they are not able to do rdm sprees and so fourth..

**Comment by grinchhh** [comment]
It does.  But what I am trying to get at it slays only on pre round. I need it more on the actual round.

**Comment by whocodes** [comment]
It slays during pre-round and they respawn when the round starts? If thats the case, it should just need a different forward. I can have a look at it later if you don't have any coding experience.


On Aug 22, 2017, at 6:06 PM, grinchhh <notifications@github.com<mailto:notifications@github.com>> wrote:


It does. But what I am trying to get at it slays only on pre round. I need it more on the actual round.

**Comment by grinchhh** [comment]
I don't have much. I found the function I believe. It should probably hook into TTT_RoundStart.

**Comment by Bara20** [comment]
@whocodes https://github.com/Bara20/TroubleinTerroristTown/blob/master/addons/sourcemod/scripting/include/ttt.inc#L173
Player will respawned before selection (deathmatch during warmup/roundend (but warmup dm should disabled by default))

**Comment by good-live** [comment]
TTT_OnRoundStart_Pre should be used to prevent that the slain players are part of the role selection.

**Comment by grinchhh** [comment]
I have been noticing using @whocodes auto slay script, it seems to bug out every morning and slaying people over and over till they leave and it moves onto the next one. It works perfectly, but I believe it needs some checks like not slaying on pre-start. As for the mass slaying, I don't have an error for it and I haven't personally seen it happened.

**Comment by Bara20** [comment]
https://github.com/Bara20/TroubleinTerroristTown/pull/203
