### ISSUE TITLE
Logs should also include steam ids

### ISSUE THREAD

**Issue by PRAWKC** [Bara20/TroubleinTerroristTown#156]
Currently Logs are like this.

`L 08/22/2017 - 01:12:20: [00:10] -> [Player1 (Innocent) damaged Player2 (Innocent) for 3 damage with bizon] - BAD ACTION`

Should look like this

`L 08/22/2017 - 01:12:20: [00:10] -> [Player1[STEAM_0:0:11101] (Innocent) damaged Player2 (Innocent) for 3 damage with bizon] - BAD ACTION`

or like this 

`L 08/22/2017 - 01:12:20: [00:10] -> [Player1[STEAM_0:0:11101] (Innocent) damaged Player2[STEAM_0:0:11101] (Innocent) for 3 damage with bizon] - BAD ACTION`

I believe logs should contain the steam id of at least the first player doing the action, because anyone can go on a TTT server when there is no admins on and start rdming with another persons name and then create a false report later on the forums saying that X person was rdming last night and they would successfully get someone else banned.

**Comment by Bara20** [comment]
I prefer steamid64/community, but we can add a config.

**Comment by PRAWKC** [comment]
Both works for me, I just think though it needs to be added, because right now people can literally rdm using another persons name and then someone else could get in trouble.

**Comment by Bara20** [comment]
mhm makes sense. I'll add it to 2.2 instead of 2.3+

**Comment by good-live** [comment]
Wouldn't it be easier to just use the sourcemod logging format (%L)

**Comment by Bara20** [comment]
Yeah, but i don't like it. For example: Bara<2><STEAM_1:1:40828751><>

**Comment by whocodes** [comment]
I believe someone has rewritten the sourcemod logging system to be simplified. but either way, knowing userid is useful (for in-game punishments) -- the last <> would be the IP address

On Aug 22, 2017, at 7:53 AM, Bara20 <notifications@github.com<mailto:notifications@github.com>> wrote:


Yeah, but i don't like it. For example: Bara<2><STEAM_1:1:40828751><>
