### ISSUE TITLE
Karma is negative on the scoreboard

### ISSUE THREAD

**Issue by Nachtfrische** [Bara20/TroubleinTerroristTown#161]
When a player dies, his karma becomes negative. Here is a screenshot to illustrate the issue:
![gasxlrdjtrasrapjn-0jvg](https://user-images.githubusercontent.com/23483247/29670737-e52f81a6-88e7-11e7-90bb-025a9dcc6def.png)

**Comment by Bara20** [comment]
Ist gewollt, damit die Liste sortiert ist (wer lebt und wer nicht) damit man die lebenden sieht sofern mehrere Spieler drauf sind.
