### ISSUE TITLE
HUD and Stations errors in logs.

### ISSUE THREAD

**Issue by omar-damaj** [Bara20/TroubleinTerroristTown#165]
Player HUD error showing a lot more in the logs but the stations one shows when people spawn them sometimes. 

L 08/25/2017 - 15:34:24: [SM] Exception reported: Language phrase "Hud PlayerName I-T" not found
L 08/25/2017 - 15:34:24: [SM] Blaming: ttt/ttt_playerhud.smx
L 08/25/2017 - 15:34:24: [SM] Call stack trace:
L 08/25/2017 - 15:34:24: [SM]   [0] Format
L 08/25/2017 - 15:34:24: [SM]   [1] Line 163, addons/sourcemod/scripting/ttt/ttt_playerhud.sp::PrepareText
L 08/25/2017 - 15:34:24: [SM]   [2] Line 90, addons/sourcemod/scripting/ttt/ttt_playerhud.sp::Timer_UpdateText

L 08/25/2017 - 15:34:27: [SM] Exception reported: Invalid timer handle 4c590311 (error 3)
L 08/25/2017 - 15:34:27: [SM] Blaming: ttt/ttt_stations.smx
L 08/25/2017 - 15:34:27: [SM] Call stack trace:
L 08/25/2017 - 15:34:27: [SM]   [0] KillTimer
L 08/25/2017 - 15:34:27: [SM]   [1] Line 179, addons/sourcemod/scripting/ttt/ttt_stations.sp::ClearTimer
L 08/25/2017 - 15:34:27: [SM]   [2] Line 349, addons/sourcemod/scripting/ttt/ttt_stations.sp::cleanupStation
L 08/25/2017 - 15:34:27: [SM]   [3] Line 194, addons/sourcemod/scripting/ttt/ttt_stations.sp::CS_OnTerminateRound
L 08/25/2017 - 15:34:27: [SM]   [5] CS_TerminateRound
L 08/25/2017 - 15:34:27: [SM]   [6] Line 3448, addons/sourcemod/scripting/ttt/ttt.sp::CheckTeams
L 08/25/2017 - 15:34:27: [SM]   [7] Line 2300, addons/sourcemod/scripting/ttt/ttt.sp::Event_PlayerDeath

L 08/25/2017 - 15:32:31: [SM] Exception reported: Invalid timer handle 4c590311 (error 3)
L 08/25/2017 - 15:32:31: [SM] Blaming: ttt/ttt_stations.smx
L 08/25/2017 - 15:32:31: [SM] Call stack trace:
L 08/25/2017 - 15:32:31: [SM]   [0] KillTimer
L 08/25/2017 - 15:32:31: [SM]   [1] Line 179, addons/sourcemod/scripting/ttt/ttt_stations.sp::ClearTimer
L 08/25/2017 - 15:32:31: [SM]   [2] Line 349, addons/sourcemod/scripting/ttt/ttt_stations.sp::cleanupStation
L 08/25/2017 - 15:32:31: [SM]   [3] Line 144, addons/sourcemod/scripting/ttt/ttt_stations.sp::Event_RoundStartPre

// Added by Bara:
 L 08/27/2017 - 15:25:53: [SM] Exception reported: Invalid timer handle fd630a01 (error 1)
L 08/27/2017 - 15:25:53: [SM] Blaming: ttt/ttt_c4_jihad.smx
L 08/27/2017 - 15:25:53: [SM] Call stack trace:
L 08/27/2017 - 15:25:53: [SM]   [0] KillTimer
L 08/27/2017 - 15:25:53: [SM]   [1] Line 874, addons/sourcemod/scripting/ttt/ttt_c4_jihad.sp::ClearTimer
L 08/27/2017 - 15:25:53: [SM]   [2] Line 187, addons/sourcemod/scripting/ttt/ttt_c4_jihad.sp::ResetGlobals
L 08/27/2017 - 15:25:53: [SM]   [3] Line 151, addons/sourcemod/scripting/ttt/ttt_c4_jihad.sp::Event_PlayerSpawn

**Comment by Bara20** [comment]
It's better to update your translations files.  ["Hud PlayerName I-T" exists. ](https://github.com/Bara20/TroubleinTerroristTown/blob/master/addons/sourcemod/translations/ttt.phrases.txt#L964)
