### ISSUE TITLE
List of possible suggestions

### ISSUE THREAD

**Issue by KrisTheCanadian** [Bara20/TroubleinTerroristTown#166]
1- In the original Garry's mod TTT. When you identified a body, you were able to see what gun was used to kill the player with, including some details like how long ago did he die. (maybe not exactly like original, but more information written in chat when identifying a body. :)

2- Golden gun (can shoot somebody, If victim is inno then the shooter dies, if victim is traitor then the traitor dies.)

3- Defibrillators (this may be more complex because bringing back somebody from the dead might have a lot of bugs)

4- Sticky bomb (plant it on a victim and you can make victim explode)

5- Something that allows you to throw props with a launcher.

6- Classic Poison dart + antidote
Theses are simple suggestions, and not issues

**Comment by Bara20** [comment]
Please one suggestion per issue.
