### ISSUE TITLE
help

### ISSUE THREAD

**Issue by Floower** [Bara20/TroubleinTerroristTown#167]
L 08/29/2017 - 17:45:01: [SM] Exception reported: Invalid Handle 0 (error: 4)
L 08/29/2017 - 17:45:01: [SM] Blaming: cameras-and-drones.smx
L 08/29/2017 - 17:45:01: [SM] Call stack trace:
L 08/29/2017 - 17:45:01: [SM]   [0] ArrayList.FindValue
L 08/29/2017 - 17:45:01: [SM]   [1] Line 782, cameras-and-drones.sp::OnPlayerRunCmd
L 08/29/2017 - 17:45:01: [SM] Exception reported: Invalid Handle 0 (error: 4)
L 08/29/2017 - 17:45:01: [SM] Blaming: cameras-and-drones.smx
L 08/29/2017 - 17:45:01: [SM] Call stack trace:
L 08/29/2017 - 17:45:01: [SM]   [0] ArrayList.FindValue
L 08/29/2017 - 17:45:01: [SM]   [1] Line 782, cameras-and-drones.sp::OnPlayerRunCmd
L 08/29/2017 - 17:55:17: [SM] Exception reported: Language phrase "No matching client" not found
L 08/29/2017 - 17:55:17: [SM] Blaming: ttt/ttt_shop.smx
L 08/29/2017 - 17:55:17: [SM] Call stack trace:
L 08/29/2017 - 17:55:17: [SM]   [0] ReplyToCommand
L 08/29/2017 - 17:55:17: [SM]   [1] Line 102, /home/travis/build/Bara20/TroubleinTerroristTown/addons/sourcemod/scripting/include/commandfilters.inc::ReplyToTargetError
L 08/29/2017 - 17:55:17: [SM]   [2] Line 892, addons/sourcemod/scripting/ttt/ttt_shop.sp::Command_SetCredits
L 08/29/2017 - 17:55:17: [SM] Exception reported: Language phrase "No matching client" not found
L 08/29/2017 - 17:55:17: [SM] Blaming: ttt/ttt_shop.smx
L 08/29/2017 - 17:55:17: [SM] Call stack trace:
L 08/29/2017 - 17:55:17: [SM]   [0] ReplyToCommand
L 08/29/2017 - 17:55:17: [SM]   [1] Line 102, /home/travis/build/Bara20/TroubleinTerroristTown/addons/sourcemod/scripting/include/commandfilters.inc::ReplyToTargetError
L 08/29/2017 - 17:55:17: [SM]   [2] Line 892, addons/sourcemod/scripting/ttt/ttt_shop.sp::Command_SetCredits
L 08/29/2017 - 18:15:47: Error log file session closed.
L 08/29/2017 - 18:54:42: SourceMod error session started
L 08/29/2017 - 18:54:42: Info (map "TTT_PrincessCraft_BETA4") (file "errors_20170829.log")
L 08/29/2017 - 18:54:42: [SM] Exception reported: Entity -1 (-1) is invalid
L 08/29/2017 - 18:54:42: [SM] Blaming: cameras-and-drones.smx
L 08/29/2017 - 18:54:42: [SM] Call stack trace:
L 08/29/2017 - 18:54:42: [SM]   [0] GetEntPropString
L 08/29/2017 - 18:54:42: [SM]   [1] Line 748, /home/keplyx/csgosl/server/csgo/addons/sourcemod/scripting/include/entity.inc::GetEntityClassname
L 08/29/2017 - 18:54:42: [SM]   [2] Line 1075, cameras-and-drones.sp::IsWeaponGear
L 08/29/2017 - 18:54:42: [SM]   [3] Line 974, cameras-and-drones.sp::CommandDrop
L 08/29/2017 - 19:20:23: Error log file session closed.

**Comment by Bara20** [comment]
@Keplyx

**Comment by Keplyx** [comment]
@Floower moved issue to https://github.com/Keplyx/cameras-and-drones/issues/2
