### ISSUE TITLE
"New" configs

### ISSUE THREAD

**Issue by Bara20** [Bara20/TroubleinTerroristTown#168]
We should go back to the old sourcemod configs. It's "better" to use and has a better compatibility between features without opening the config for each feature.

We could use this one: https://forums.alliedmods.net/showthread.php?p=1862389#post1862389

@good-live

**Comment by good-live** [comment]
https://forums.alliedmods.net/showthread.php?t=233282 would also be an option, but I'm fine with AutoExecConfig :+1:

Maybe another point to discuss would be whether we cache the values in local variables or directly grab them from the ConVar?

**Comment by whocodes** [comment]
Personally I think key-value configs are better.


SourceMod is basically naturally prepared to handle it either way, cvars in cfg/sourcemod and other configs in sourcemod/configs

On Aug 30, 2017, at 7:15 AM, good-live <notifications@github.com<mailto:notifications@github.com>> wrote:


https://forums.alliedmods.net/showthread.php?t=233282 would also be an option, but I'm fine with AutoExecConfig 👍

Maybe another point to discuss would be whether we cache the values in local variables or directly grab them from the ConVar?

**Comment by good-live** [comment]
Are there any specific reasons why you prefer KeyValue configs @whocodes ?

**Comment by whocodes** [comment]
I don't prefer them in the way they're implemented in this plugin, but you could easily separate things into categories.

"Settings"
{
       "general"
       {
              "setting"       "value"
       }

       "karma"
       {
               "setting"       "value"
       }
}




It just looks neater, can make things a lot easier to navigate, and though it looks like it takes up a lot more space in that small example, when you have everything incorporated it can be space efficient.

I made a really simple include for it when the new SourceMod syntax was being made, its on my GitHub called configloader. Could very easily be improved and also made to create a cvar with a ttt_ prefix, and make it use the category in the cvar (so ttt_general_ as the prefix).

🤷🏻‍♂️

Sent from my iPhone

On Aug 31, 2017, at 4:23 AM, good-live <notifications@github.com<mailto:notifications@github.com>> wrote:


Are there any specific reasons why you prefer KeyValue configs @whocodes<https://github.com/whocodes> ?

**Comment by Bara20** [comment]
@good-live @whocodes

Here are 3 examples...
1 - [Current ttt config](https://pastebin.com/9mSK0jma)
2 - [Current ttt config with categories](https://pastebin.com/bnFWpSkb)
3 - [Default configs](https://pastebin.com/uGKgjjrX) _I know it's the config from hosties, but he's enough cvars as demonstrate._

**Comment by popey456963** [comment]
@Bara20 I'm interested, which option did you pick?

**Comment by Bara20** [comment]
3 @popey456963

**Comment by Bara20** [comment]
https://github.com/Bara20/TroubleinTerroristTown/pull/203
