### ISSUE TITLE
What does "ttt_give_weapons_on_failed_start" do?

### ISSUE THREAD

**Issue by popey456963** [Bara20/TroubleinTerroristTown#171]
The description of `Give player weapons on a fail start?` doesn't provide much light on this.

 - What is a failed start?
 - Does it give default role weapons?
 - Should I enable or disable this?

**Comment by popey456963** [comment]
Oh, actually, looked down in the config file and found these to answer the second question:

```
        "ttt_give_weapons_fail_start_primary"
        {
                "value"         "ak47"
                "description"           "What primary weapon do you want? (WITHOUT 'weapon_' TAG!)"
        }
        "ttt_give_weapons_fail_start_secondary"
        {
                "value"         "deagle"
                "description"           "What primary weapon do you want? (WITHOUT 'weapon_' TAG!)"
        }
```

**Comment by Bara20** [comment]
> What is a failed start
When the round can't start (example: too less players).

> Should I enable or disable this?
Enable it, if you want deathmatch or other custom stuff.
