### ISSUE TITLE
Taser forward in `ttt.inc`

### ISSUE THREAD

**Issue by popey456963** [Bara20/TroubleinTerroristTown#175]
Would be useful, :)

**Comment by Bara20** [comment]
What kind of taser forward? ttt.inc has nothing to do with taser since we've [ttt_taser](https://github.com/Bara20/TroubleinTerroristTown/blob/master/addons/sourcemod/scripting/ttt/ttt_taser.sp)

**Comment by popey456963** [comment]
Ah, I'm sorry, I didn't completely understand how the repository was laid out.  I'm saying it would be nice to have another include file,  perhaps `ttt_taser.inc`, which included a forward.  This would be called everytime someone was tased and reveal the ClientID.

**Comment by Bobakanoosh** [comment]
#190
