### ISSUE TITLE
Detective icon gets transferred to other players

### ISSUE THREAD

**Issue by Nachtfrische** [Bara20/TroubleinTerroristTown#176]
When the detective is alive and goes to the spectator team, his detective icon (and Auras etc.) moves to the player he is currently spectating. This leads to players thinking they are talking to a detective because of the symbol, even though they are not.

**Comment by good-live** [comment]
Does this only occure with the Detective Icon?
Last time i've tested it with the traitor icon and couldn't reproduce it,

**Comment by Nachtfrische** [comment]
It might only occure with detectives. I haven't tested the issue myself, I've only got a report from an admin of my community.

**Comment by good-live** [comment]
Can you test that?

**Comment by NicronS** [comment]
We have this same issue it's mostly when someone moves to spectate without being killed mid round, i'll try to get screenshots tonight on our server.

**Comment by Bara20** [comment]
We could add a check on jointeam with [AddCommandListener](http://sourcemod.net/new-api/console/AddCommandListener). @good-live

**Comment by good-live** [comment]
Why not simply hook the team change event?

**Comment by good-live** [comment]
@Nachtfrische @NicronS Can you test this again?

**Comment by NicronS** [comment]
i'll add it to our code tonight and test it.

**Comment by good-live** [comment]
And news?

**Comment by NicronS** [comment]
It seems to work in our dev environment, if anything changes in production i'lll let you know.
