### ISSUE TITLE
Grabber mod

### ISSUE THREAD

**Issue by Pixel333** [Bara20/TroubleinTerroristTown#177]
Hi, I have one question. I have a server on which there are blocks that can be taken using the grabber mode. This is used to mark the dead. I want to know if you can disable take blocks through grabber mod (in TTT). With a grabber mode, you would only take bodies, not blocks. With blocks players can jump to sky box...

Thanks

**Comment by good-live** [comment]
The grabber mod is made for moving props. What might be possible is a check, whether the prop is below you or not.

**Comment by Pixel333** [comment]
player jumps to the block and fired it to sky, how can i disable it?

**Comment by Pixel333** [comment]
and can you create that control for me, please

**Comment by whocodes** [comment]
You can add a filter to only allow ragdolls to be picked up but several maps are made with the idea that grabbermod is enabled.
