### ISSUE TITLE
Attempted to create unknown entity type weapon_zm_shotgun!

### ISSUE THREAD

**Issue by NicronS** [Bara20/TroubleinTerroristTown#185]
`
Attempted to create unknown entity type weapon_zm_shotgun!
Can't init weapon_zm_shotgun
Attempted to create unknown entity type weapon_zm_sledge!
Can't init weapon_zm_sledge
Attempted to create unknown entity type ttt_traitor_button!
Can't init ttt_traitor_button
Attempted to create unknown entity type ttt_Detective_button!
Can't init ttt_Detective_button
Attempted to create unknown entity type ttt_random_ammo!
Can't init ttt_random_ammo
Attempted to create unknown entity type ttt_random_ammo!
Can't init ttt_random_ammo
Attempted to create unknown entity type ttt_random_ammo!
Can't init ttt_random_ammo
Attempted to create unknown entity type ttt_random_weapon!
Can't init ttt_random_weapon
`

My server console is constantly getting spammed with the error above.

**Comment by good-live** [comment]
This occures due to the map entitys. Is it converted from gmod?

**Comment by Bara20** [comment]
Looks like no plugin related issue. I'll close it.
