### ISSUE TITLE
Can't kill people in the first second

### ISSUE THREAD

**Issue by throwawayttt49** [Bara20/TroubleinTerroristTown#186]
If you shoot someone in the first second of the round they are listed as a teammate and no damage is done till after and it prints in chat you attacked someone exposing your role

**Comment by Bara20** [comment]
@throwawayttt49 could you try this little feature https://github.com/Bara20/TroubleinTerroristTown/commit/0886c8b7d7076d0f328e8878f26bf79c1c225a99 and let me know if it help.

**Comment by Bara20** [comment]
With the merge of #203 I'll close this issue for inactivity. @throwawayttt49
