### ISSUE TITLE
Custom skin issue

### ISSUE THREAD

**Issue by rsgua** [Bara20/TroubleinTerroristTown#192]
Hello
I have some problem...
if i set ttt_update_client_model to 1 and that update client models and i cant use custom model from vip.
and if i set ttt_update_client_model 0 - i can use custom model from vip plugin but players set model what they had before the start game(set role).
Why you don`t change team and role some other way so that set some custom from other plugins.

**Comment by Bara20** [comment]
You could add [TTT_OnModelUpdate](https://github.com/Bara20/TroubleinTerroristTown/commit/cb976a525ef17753e4bb834c3eb635657efbb6c5) to your vip plugin/feature if you want custom models.
