### ISSUE TITLE
Add 152, smx name

### ISSUE THREAD

**Issue by millerze** [Bara20/TroubleinTerroristTown#195]
+	file = "futuristicgrenades.smx",

L 11/03/2017 - 11:17:50: [SM] Unable to load plugin "ttt/ttt_futuristicgrenades.smx": Could not find required plugin "futuristicgrenades"

Should it be named ttt_futuristicgrenades.smx for the file above?

**Comment by millerze** [comment]
Also this?

L 11/03/2017 - 12:46:32: [SM] Exception reported: You must have this plugin as base plugin for this items: https://forums.alliedmods.net/showthread.php?p=2499362
L 11/03/2017 - 12:46:32: [SM] Blaming: ttt/futuristicgrenades.smx
L 11/03/2017 - 12:46:32: [SM] Call stack trace:
L 11/03/2017 - 12:46:32: [SM]   [0] SetFailState
L 11/03/2017 - 12:46:32: [SM]   [1] Line 72, ttt/ttt_futuristicgrenades.sp::OnAllPluginsLoaded

**Comment by Bara20** [comment]
No, that's should right but I haven't test it. You've [this plugin](https://forums.alliedmods.net/showthread.php?p=2499362) on your server, that's a requirement this this feature/item.

**Comment by millerze** [comment]
Ah yes, I just realized that and I've grabbed that base plugin.  I didn't realize it required the other plugin as well.  My apologies!
