### ISSUE TITLE
Sprint doesn't work

### ISSUE THREAD

**Issue by Bara20** [Bara20/TroubleinTerroristTown#199]
00:48 - SkippY: Sprint how to activate?
00:49 - Bara: Try E (+use)
00:50 - SkippY: didnt work

**Comment by omar-damaj** [comment]
For me it works by default without having to buy the item so all players have it activated. If a player presses E they sprint.

**Comment by Bara20** [comment]
https://github.com/Bara20/TroubleinTerroristTown/pull/203
