### ISSUE TITLE
Karma bans not going through until end of round

### ISSUE THREAD

**Issue by omar-damaj** [Bara20/TroubleinTerroristTown#201]
Is there a way we can have Karma bans go through at any time a player reaches the karma ban amount when ttt_public_karma is set to 0? At the moment it waits until the end of round when everyone's karma gets updated until the player gets banned.

**Comment by Bara20** [comment]
Is fixed and will be uploaded after config update (today or tomorrow)

**Comment by Bara20** [comment]
I'll reopen this again since it's not finally fixed.

**Comment by Bara20** [comment]
https://github.com/Bara20/TroubleinTerroristTown/pull/203

**Comment by omar-damaj** [comment]
Fixed as tested. Karma bans are instant when player is alive.
