### ISSUE TITLE
Karma native get failure

### ISSUE THREAD

**Issue by popey456963** [Bara20/TroubleinTerroristTown#208]
Trying to get my TTT server slowly back to the master, after a few weeks of chucking all my stuff in plugins instead of changing the base code (in truly horrendous and broken ways) took the leap today.  Managed to fix most of the issues caused by my own stupidity, but this doesn't seem to be related to me.

```
L 11/13/2017 - 12:40:41: [SM] Exception reported: Invalid parameter number: 2
L 11/13/2017 - 12:40:41: [SM] Blaming: ttt/ttt.smx
L 11/13/2017 - 12:40:41: [SM] Call stack trace:
L 11/13/2017 - 12:40:41: [SM]   [0] GetNativeCell
L 11/13/2017 - 12:40:41: [SM]   [1] Line 21, addons/sourcemod/scripting/ttt/core/natives.sp::Native_GetClientKarma
L 11/13/2017 - 12:40:41: [SM]   [3] TTT_GetClientKarma
L 11/13/2017 - 12:40:41: [SM]   [4] Line 90, addons/sourcemod/scripting/ttt/ttt_player_hud.sp::PrepareText
L 11/13/2017 - 12:40:41: [SM]   [5] Line 75, addons/sourcemod/scripting/ttt/ttt_player_hud.sp::Timer_UpdateText
```

I can be fairly sure that the DB is functional and that karma for all players involved do exist, since an older version of TTT appears to work well.  Any ideas why this appears on the server console every few seconds?

**Comment by good-live** [comment]
Are you using the master version of ttt_player_hud?

**Comment by popey456963** [comment]
Yep, 1263, downloaded the latest version maybe a dozen hours ago.

**Comment by Bara20** [comment]
Wait... "ttt_player_hud.sp" is a old file.

**Comment by popey456963** [comment]
@Bara20 Crap, my bad, you're right.  Still had both versions of the file.
