### ISSUE TITLE
Player can mute other players (Specmenu)

### ISSUE THREAD

**Issue by kikoplg** [Bara20/TroubleinTerroristTown#21]
Player can mute other players (for themselves) in Specmenu

**Comment by kikoplg** [comment]
https://painlessgaming.eu/thread/399-lebenden-voice-chat-w%C3%A4hrend-des-todes/?postID=2463#post2463

**Comment by kikoplg** [comment]
1) Spieler nach vorne 
2) Spieler zurück 
3) mute lebende Spieler
4) mute tote Spieler
5) special command welcher ich in einer config festlegen kann ?? zB. sm_rtv (nice2have, muss aber nicht)

**Comment by Bara20** [comment]
|------------------------------|
|    Spec Menu                |
|------------------------------|
|1. Next Player                |
|2. Prev Player               |
|------------------------------|
| Muted: Yes/No              |
| 3. (Un)Mute                  |
|------------------------------|
| 4. Mute Living players  |
| 5. Mute Dead Players   |
|------------------------------|
| 6. Custom commands   |
|------------------------------|

**Comment by kikoplg** [comment]
https://gyazo.com/ccc04cad1d0b201744344b6d901f3877

**Comment by kikoplg** [comment]
wäre sehr wichtig.

**Comment by kikoplg** [comment]
Done!
