### ISSUE TITLE
Wallhack is broken

### ISSUE THREAD

**Issue by Nachtfrische** [Bara20/TroubleinTerroristTown#211]
The wallhack is broken in the newer versions of TTT. I've just version 1263 and it's not working there. I've rolled back all the plugins to version 1223 from the 21 September and it's working fine on the older version.
I would assume that some update broke it along the way.

How to reproduce: 
Get the newest version and buy the wallhack. There will be no glow around any player.

**Comment by Bara20** [comment]
https://github.com/Bara20/TroubleinTerroristTown/pull/203
