### ISSUE TITLE
ID Name in Shop

### ISSUE THREAD

**Issue by omar-damaj** [Bara20/TroubleinTerroristTown#215]
The name for ID for innocents is showing as the Traitor name. 
The Traitor name shows up fine. 

// The name of this in Innocent Shop
// -
// Default: "ID"
id_name_innocent "ID card (Type !id to show your innocence)"

// The name of this in Traitor Shop
// -
// Default: "(Fake) ID"
id_name_traitor "FAKE ID card (Type !id to show your innocence)"

**Comment by Bara20** [comment]
Sure you've the right item name for traitors?
https://github.com/Bara20/TroubleinTerroristTown/commit/d836f018b34326bfd9f077cf8915f35bb269b073 should fix this issue

**Comment by omar-damaj** [comment]
Fixed. Thank you!
