### ISSUE TITLE
Detective Taser Doing Damage

### ISSUE THREAD

**Issue by omar-damaj** [Bara20/TroubleinTerroristTown#216]
Detective Taser doing damage when set to 0

// The amount of damage a taser deals for detectives and innocents
// -
// Default: "0"
ta_damage "0"

// The amount of damage a taser deals for traitors
// -
// Default: "0"
ta_traitor_damage "200"

**Comment by Bara20** [comment]
Give build id 1309 a chance ( https://github.com/Bara20/TroubleinTerroristTown/commit/81fc1a2f4e247838efeac82d0a6db96d36cb8364 )

**Comment by omar-damaj** [comment]
Fixed! Thank you Bara
