### ISSUE TITLE
Black Hole Death

### ISSUE THREAD

**Issue by omar-damaj** [Bara20/TroubleinTerroristTown#217]
If you die from a black hole, your body becomes unIDable. 
It just becomes a ragdoll that noone can move or ID and you show up as alive in the scoreboard.

**Comment by Bara20** [comment]
Any errors? I think the problems comes with [SDKHooks_TakeDamage](https://github.com/Rachnus/Futuristic-Grenades/blob/master/scripting/futuristicgrenades.sp#L706), because we've no player as attacker.

**Comment by omar-damaj** [comment]
Fixed! Thank you!
