### ISSUE TITLE
Configs not generating 2.3

### ISSUE THREAD

**Issue by Bobakanoosh** [Bara20/TroubleinTerroristTown#221]
Hey!

I noticed that dronescameras, futuristic grenades, and parachute all have configs that dont generate. I checked in cfg/ttt/, and cfg/sourcemod/, and /sourcemod/configs, and nothing.

List of configs I got: https://i.imgur.com/l3vaDnF.png

**Comment by Bobakanoosh** [comment]
Okay sorry, partially my fault.
`L 11/15/2017 - 10:48:39: [SM] Unable to load plugin "ttt\ttt_futuristicgrenades.smx": Could not find required plugin "futuristicgrenades"
L 11/15/2017 - 10:48:39: [SM] Unable to load plugin "ttt\ttt_parachute.smx": Could not find required plugin "AdvancedParachute"`

However, it would be nice if you put these plugins it requires in the download on csgottt.com :P

**Comment by Bobakanoosh** [comment]
Is AdvancedParachute == https://forums.alliedmods.net/showthread.php?p=580269?

**Comment by Bobakanoosh** [comment]
Also, related, `L 11/15/2017 - 10:48:39: [SM] Unable to load plugin "ttt\ttt_dronescameras.smx": Native "BuyPlayerGear" was not found`

**Comment by Bara20** [comment]
Those aren't requirements, just optional plugins + features.

Advanced Parachute: https://forums.alliedmods.net/showthread.php?p=2534158
Cameras and Drones: https://forums.alliedmods.net/showthread.php?p=2537127
Futuristic Grenades: https://forums.alliedmods.net/showthread.php?p=2499362

**Comment by Bara20** [comment]
I've moved all 3 ttt-plugins into disabled folder.
