### ISSUE TITLE
PlayerHud config file causing errors

### ISSUE THREAD

**Issue by popey456963** [Bara20/TroubleinTerroristTown#223]
PlayerHud is unique in the sense that it includes multiple lines.  Although I haven't tested it, I would assume it causes errors when run:

```
// Default: "{NAME}: {PLAYERNAME}
{KARMA}: {PLAYERKARMA}"
```

**Comment by Bara20** [comment]
We could move it to translations and remove all "Hud PlayerName X-X" translations (makes us problems with html tags and http://translator.mitchdempsey.com/sourcemod_plugins/158 )

@good-live what do you think?
