### ISSUE TITLE
Players with reserved slot admin flag can see who are T's when dead.

### ISSUE THREAD

**Issue by botarnold** [Bara20/TroubleinTerroristTown#27]
I think this feature was intended for Admins to identify players even while dead. however the VIP players on my servers despite getting "a" and a custom "r" admin flag, they could still see who the living T's were while dead.

**Comment by good-live** [comment]
Take a look at this ConVar in icon.cfg: ttt_icon_dead_admin

**Comment by Bara20** [comment]
You can add multiple flags to this cvar.
