### ISSUE TITLE
Glow - Invalid Entity

### ISSUE THREAD

**Issue by good-live** [Bara20/TroubleinTerroristTown#29]
See alliedmodders post: https://forums.alliedmods.net/showpost.php?p=2431466&postcount=366

Maybe there should be a check if the returned entity of CPS is valid.
https://github.com/Bara20/TroubleinTerroristTown/blob/master/addons/sourcemod/scripting/ttt/ttt_wallhack.sp#L278

**Comment by Bara20** [comment]
UnhookGlow wird nur eingeführt wenn der Spieler valid ist (sprich nach einem TTT_IsClientValid). Man könnte noch ein if (x > 0) einbauen - was aber bei TTT_IsClientValid bei ist.

**Comment by good-live** [comment]
Es geht mir eher um den Teil: CPS_SetSkin(client, sModel, CPS_RENDER) zum Einen kommt da laut include garkein return, aber seid Version 3.0 (laut CPS Thread) wird das Model entity returned. Offensichtlich kann dort auch ein -1 returned werden, wenn der Client valid ist. (Vllt. wenn die Entity Grenze erreicht ist?)
Aufjendefall sollte der return vom CPS überprüft werden.

**Comment by Bara20** [comment]
:facepunch: That c&p fail

Should be fixed now.

**Comment by good-live** [comment]
L 07/02/2016 - 13:53:28: [SM] Exception reported: Property "m_bShouldGlow" not found (entity 1/player)
L 07/02/2016 - 13:53:28: [SM] Blaming: ttt/ttt_tagrenade.smx()
L 07/02/2016 - 13:53:28: [SM] Call stack trace:
L 07/02/2016 - 13:53:28: [SM] [0] SetEntProp
L 07/02/2016 - 13:53:28: [SM] [1] Line 349, addons/sourcemod/scripting/ttt/ttt_tagrenade.sp::UnhookGlow()
L 07/02/2016 - 13:53:28: [SM] [2] Line 85, addons/sourcemod/scripting/ttt/ttt_tagrenade.sp::TTT_OnUpdate3()
L 07/02/2016 - 13:53:28: [SM] [4] Call_Finish
L 07/02/2016 - 13:53:28: [SM] [5] Line 2693, addons/sourcemod/scripting/ttt/ttt.sp::Timer_3()
