### ISSUE TITLE
Overlay on round end not working properly

### ISSUE THREAD

**Issue by igortomiatti** [Bara20/TroubleinTerroristTown#30]
When the config "ttt_end_with_detective" is activated, only the traitor overlay works.

When the config is deactivated all round final overlays works correctly.

**Comment by Bara20** [comment]
Should be fixed with https://github.com/Bara20/TroubleinTerroristTown/commit/32dc2c449a44e47cd8eaedaa39b3c64fd40c6b58

**Comment by Bara20** [comment]
No reactions since opening. Seems fixed.
