### ISSUE TITLE
Add New Release

### ISSUE THREAD

**Issue by popey456963** [Bara20/TroubleinTerroristTown#31]
Your last release seems to be from over 8 months ago.  I am yet to see any recent releases.  Perhaps you should think about adding a more recent one?

**Comment by good-live** [comment]
https://github.com/Bara20/TroubleinTerroristTown/commit/9dfcc5c10fd17473491ba846f5d7d97ae007b660

**Comment by popey456963** [comment]
Thanks for the speedy reply, but I must be missing something.  That doesn't seem a release, just a merge with the master branch.  I say this because I seem to be struggling to compile my own .smx files, the build.sh script keeps on erroring out whenever I am running it.

**Comment by good-live** [comment]
Well merging master into stable means: the current dev status is stable. Which i would call a new release.

**Comment by popey456963** [comment]
I guess that is very true indeed, in which case, apologies for lack of ability to communicate.

I more meant is there a build of the latest .smx files that have been created relatively recently (the old version create a very strange jumping bug on the latest version of CS:GO).  I am trying to compile them myself but seem to lack the ability to find out what $1-$6 are meant to be.  (Note, realise they're parameters to the command line call, just can't figure out what values create a build that doesn't miserably break).

**Comment by popey456963** [comment]
I'll close this in lieu of creating a better issue.

**Comment by good-live** [comment]
You can download the latest stable build on csgottt.com

**Comment by popey456963** [comment]
That website did seem to intrigue me.  I can only find versions starting 1.8 and 1.9 there.  I am yet to find the 2.0x build that seems to work.  If those are the latest builds that are supposed to work, maybe I'll have to start a bug issue about jumping around (as in, you jump, you go about 100x further than normal and have autobhop on)

**Comment by Bara20** [comment]
stable-Table 369 (and lower) is the old-stable version (2.0.X).

**Comment by popey456963** [comment]
Oh I see now.  I have absolutely no idea what I was on earlier.  Thanks so much for being so patient through my idiocy.
