### ISSUE TITLE
C4 never showed up in T menu

### ISSUE THREAD

**Issue by botarnold** [Bara20/TroubleinTerroristTown#32]
The pplugin runs fine but no one can see the C4 or jihad bomb in the T shop.

**Comment by good-live** [comment]
It works fine for me. Any errors? Are you sure it is loaded? Try reloading manually.

**Comment by botarnold** [comment]
there's no errors related to ttt_c4_jihad plugin. The plugin is loaded correctly tho, there is just no way to purchase it.

**Comment by good-live** [comment]
As i said it works fine for me. Without any informations i can't do much.

**Comment by botarnold** [comment]
It works when I reload it. But not when I load it on map change because im running multiple modes on this server.

**Comment by good-live** [comment]
Seems like a issue on your side.
