### ISSUE TITLE
Glow, wallhack, tagrenade, stations error spams

### ISSUE THREAD

**Issue by botarnold** [Bara20/TroubleinTerroristTown#33]
L 07/16/2016 - 01:12:32: [SM] Native "SetEntProp" reported: Property "m_bShouldGlow" not found (entity 5/player)
L 07/16/2016 - 01:12:32: [SM] Displaying call stack trace for plugin "disabled/ttt/ttt_wallhack.smx":
L 07/16/2016 - 01:12:32: [SM]   [0]  Line 278, ttt_wallhack.sp::UnhookGlow()
L 07/16/2016 - 01:12:32: [SM]   [1]  Line 91, ttt_wallhack.sp::TTT_OnUpdate3()
L 07/16/2016 - 01:12:32: [SM] Native "SetEntProp" reported: Property "m_bShouldGlow" not found (entity 13/player)
L 07/16/2016 - 01:12:32: [SM] Displaying call stack trace for plugin "disabled/ttt/ttt_glow.smx":
L 07/16/2016 - 01:12:32: [SM]   [0]  Line 178, ttt_glow.sp::UnhookGlow()
L 07/16/2016 - 01:12:32: [SM]   [1]  Line 66, ttt_glow.sp::TTT_OnUpdate3()
L 07/16/2016 - 01:12:32: [SM] Native "SetEntProp" reported: Property "m_bShouldGlow" not found (entity 13/player)
L 07/16/2016 - 01:12:32: [SM] Displaying call stack trace for plugin "disabled/ttt/ttt_tagrenade.smx":
L 07/16/2016 - 01:12:32: [SM]   [0]  Line 349, ttt_tagrenade.sp::UnhookGlow()
L 07/16/2016 - 01:12:32: [SM]   [1]  Line 85, ttt_tagrenade.sp::TTT_OnUpdate3()
L 07/16/2016 - 01:12:32: [SM] Native "SetEntProp" reported: Property "m_bShouldGlow" not found (entity 13/player)
L 07/16/2016 - 01:12:32: [SM] Displaying call stack trace for plugin "disabled/ttt/ttt_wallhack.smx":
L 07/16/2016 - 01:12:32: [SM]   [0]  Line 278, ttt_wallhack.sp::UnhookGlow()
L 07/16/2016 - 01:12:32: [SM]   [1]  Line 91, ttt_wallhack.sp::TTT_OnUpdate3()
L 07/16/2016 - 01:12:33: [SM] Native "IsPlayerAlive" reported: Invalid client index 0
L 07/16/2016 - 01:12:33: [SM] Displaying call stack trace for plugin "disabled/ttt/ttt_stations.smx":
L 07/16/2016 - 01:12:33: [SM]   [0]  Line 146, ttt_stations.sp::TTT_OnUpdate5()

The latest version are generating these errors.

**Comment by good-live** [comment]
#29
