### ISSUE TITLE
TTT-Iceknife Error on join

### ISSUE THREAD

**Issue by good-live** [Bara20/TroubleinTerroristTown#37]
L 07/23/2016 - 09:00:30: "good_live<3><STEAM_1:1:50109713><>" STEAM USERID validated
L 07/23/2016 - 09:00:31: [SM] Exception reported: Entity 2 (2) is invalid
L 07/23/2016 - 09:00:31: [SM] Blaming: ttt/ttt_iceknife.smx()
L 07/23/2016 - 09:00:31: [SM] Call stack trace:
L 07/23/2016 - 09:00:31: [SM] [0] SetEntProp
L 07/23/2016 - 09:00:31: [SM] [1] Line 250, C:\Users\User\AppData\Roaming\spedit\sourcepawn\configs\sm_1_8_5914\include\entity_prop_stocks.inc::SetEntityMoveType()
L 07/23/2016 - 09:00:31: [SM] [2] Line 139, C:\Users\User\Documents\GitHub\TroubleinTerroristTown\addons\sourcemod\scripting\ttt\ttt_iceknife.sp::ResetIceK()
L 07/23/2016 - 09:00:31: [SM] [3] Line 98, C:\Users\User\Documents\GitHub\TroubleinTerroristTown\addons\sourcemod\scripting\ttt\ttt_iceknife.sp::OnClientDisconnect()

**Comment by good-live** [comment]
Happens just some times.

**Comment by Bara20** [comment]
Should fixed with https://github.com/Bara20/TroubleinTerroristTown/commit/9106f0817888040f908246eda90ccfbc9b8ee79a
