### ISSUE TITLE
Talk Bug

### ISSUE THREAD

**Issue by Chickenw** [Bara20/TroubleinTerroristTown#42]
Okay So im confused on that ticket message said create new issue per bug so im guessing make a Issue for each bug:P
So The Talking bug we have here is how it works
Player's join the server as the map changes to a fresh map. Everyone can talk during the pre start(Before roles are given i have it set to 20 seconds) At the end of the run on who ever wins. Who ever is alive can talk on next round pre start Long as they did not die. But if you died you can only hear them until the roles are given out.

**Comment by good-live** [comment]
Yeah seems like i forgot some stuff upon changing the talkoverride. Im goign to take a look at it in ~1 Week

**Comment by good-live** [comment]
Just take the Version before that commit

**Comment by Chickenw** [comment]
Would When people join be related to this too? When people join in a mid match they can talk to the a live xD

**Comment by good-live** [comment]
Yeah that's related to this aswell.

**Comment by Chickenw** [comment]
Thank you ill just roll it back a bit:P We are running the newest one now and so far its good 25 people and seems to be running good:P

**Comment by good-live** [comment]
Can you try it with this commit?

**Comment by Chickenw** [comment]
Sure thing i will run some test with it today:)

**Comment by Chickenw** [comment]
We just got done testing this and it seems to work fine:) When the round ends that 2-3seconds Who ever is a live can't hear the dead untill it starts again but i dont see that being a big problem:D
