### ISSUE TITLE
Option to have Server Broadcasting of Taser Shots

### ISSUE THREAD

**Issue by popey456963** [Bara20/TroubleinTerroristTown#43]
Is it currently possible, or would it be possible to have an option in the config files to enable tasers to broadcast to all players when someone gets tasered?

**Comment by iNilo** [comment]
I'll look into this

**Comment by iNilo** [comment]
Implemented yet bugged ?

**Comment by Bara20** [comment]
I'll close it, if anyone find a bug - create a new issue.
