### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by Chickenw** [Bara20/TroubleinTerroristTown#44]
Hello so my error logs are spammed with this
`L 08/19/2016 - 13:31:27: [SM] Exception reported: Property "m_bShouldGlow" not found (entity 4/player)
L 08/19/2016 - 13:31:27: [SM] Blaming: ttt_glow.smx()
L 08/19/2016 - 13:31:27: [SM] Call stack trace:
L 08/19/2016 - 13:31:27: [SM]   [0] SetEntProp
L 08/19/2016 - 13:31:27: [SM]   [1] Line 187, ttt_glow.sp::UnhookGlow()
L 08/19/2016 - 13:31:27: [SM]   [2] Line 57, ttt_glow.sp::Event_RoundReset()
L 08/19/2016 - 13:31:27: [SM]   [4] CS_TerminateRound
L 08/19/2016 - 13:31:27: [SM]   [5] Line 2652, ttt.sp::CheckTeams()
L 08/19/2016 - 13:31:27: [SM]   [6] Line 1753, ttt.sp::Event_PlayerDeath()
L 08/19/2016 - 13:31:27: [SM] Exception reported: Property "m_bShouldGlow" not found (entity 4/player)
L 08/19/2016 - 13:31:27: [SM] Blaming: ttt_tagrenade.smx()
L 08/19/2016 - 13:31:27: [SM] Call stack trace:
L 08/19/2016 - 13:31:27: [SM]   [0] SetEntProp
L 08/19/2016 - 13:31:27: [SM]   [1] Line 358, ttt_tagrenade.sp::UnhookGlow()
L 08/19/2016 - 13:31:27: [SM]   [2] Line 103, ttt_tagrenade.sp::Event_RoundReset()
L 08/19/2016 - 13:31:27: [SM]   [4] CS_TerminateRound
L 08/19/2016 - 13:31:27: [SM]   [5] Line 2652, ttt.sp::CheckTeams()
L 08/19/2016 - 13:31:27: [SM]   [6] Line 1753, ttt.sp::Event_PlayerDeath()
L 08/19/2016 - 13:31:27: [SM] Exception reported: Property "m_bShouldGlow" not found (entity 4/player)
L 08/19/2016 - 13:31:27: [SM] Blaming: ttt_wallhack.smx()
L 08/19/2016 - 13:31:27: [SM] Call stack trace:
L 08/19/2016 - 13:31:27: [SM]   [0] SetEntProp
L 08/19/2016 - 13:31:27: [SM]   [1] Line 287, ttt_wallhack.sp::UnhookGlow()
L 08/19/2016 - 13:31:27: [SM]   [2] Line 114, ttt_wallhack.sp::Event_RoundReset()
L 08/19/2016 - 13:31:27: [SM]   [4] CS_TerminateRound
L 08/19/2016 - 13:31:27: [SM]   [5] Line 2652, ttt.sp::CheckTeams()
L 08/19/2016 - 13:31:27: [SM]   [6] Line 1753, ttt.sp::Event_PlayerDeath()`

**Comment by good-live** [comment]
This an already known Problem. Disable glow, Wallhack and Tagrenade to stop this error spam.
