### ISSUE TITLE
Credits doing weird stuff

### ISSUE THREAD

**Issue by iNilo** [Bara20/TroubleinTerroristTown#45]
I've implemented 3 forwards

```
public Action TTT_OnItemPurchased(int client, const char[] itemshort)
{
      PrintToConsoleAll("[debug] [TTT_OnItemPurchased] [client = %N | itemshort = %s]",client,itemshort);
}

public TTT_OnCreditsChanged(int client, int &credits)
{
	PrintToConsoleAll("[debug] [TTT_OnCreditsChanged] [client = %N | credits = %i]",client,credits);
}

public Action TTT_OnCreditsChanged_Pre(int client, int oldcredits, int &newcredits)
{
	PrintToConsoleAll("[debug] [TTT_OnCreditsChanged_Pre] [client = %N | old = %i || new = %i]",client,oldcredits,newcredits);
	PrintToConsoleAll("[debug] [manual maths] [current credits = %i | new credit amount will be %i | meaning %i got added",TTT_GetClientCredits(client),newcredits,(newcredits - TTT_GetClientCredits(client)));
}
```

This is the output... whats going on here ?

> [debug] [TTT_OnCreditsChanged_Pre] [client = iNilo | old = 390 || new = 7631471]
>[debug] [manual maths] [current credits = 390 | new credit amount will be 7631471 | meaning 7631081 got added
>[debug] [TTT_OnCreditsChanged] [client = iNilo | credits = 7631471]

**Comment by popey456963** [comment]
Note the reason we're doing this debugging was because of some incredibly weird stuff whereupon innocents winning the round would receive 6-10x the amount of credits we wanted them to receive.  Or, seemingly, a 10k bonus for winning that wasn't in the config.

**Comment by good-live** [comment]
Lol i haven't seen any behaviour like this yet. Which Version?.

**Comment by popey456963** [comment]
376, as far as I know.

**Comment by iNilo** [comment]
Installed  ttt-dev-1.8-152081980-e050a4f


https://github.com/Bara20/TroubleinTerroristTown/commit/e050a4f

>[debug] [TTT_OnCreditsChanged_Pre] [client = iNilo | old = 14492 || new = 14492]
>[debug] [manual maths] [current credits = 14492 | new credit amount will be 14492 | meaning -14492 got added
>[debug] [TTT_OnCreditsChanged] [client = iNilo | credits = 1]

**Comment by iNilo** [comment]
Whats going on here ? Q_Q

**Comment by popey456963** [comment]
We don't appear to have a ttt_shop.cfg?

**Comment by popey456963** [comment]
![](http://i.imgur.com/pY5raWN.png)

Are the files we have.

**Comment by good-live** [comment]
My Fault its shop.cfg in the ttt folder.

**Comment by popey456963** [comment]
Apologies, shoulda worked that out.

https://gist.github.com/popey456963/9ae37c675ed1c1b1baf17159b07cbbbd

**Comment by good-live** [comment]
When exactly does this happen? Is it reproducable?

**Comment by popey456963** [comment]
Yep, appears to happen absolutely every time someone kills another player.  Gives various strange results ranging from negative values and massive values.

**Comment by Bara20** [comment]
Looks funny ;D

**Comment by Bara20** [comment]
credits = RoundToNearest((credits) * (TTT_GetClientKarma(client) * 0.01));
In addCredits stock @good_live why?

**Comment by good-live** [comment]
I have absoloutely no idea :D Goign to remove it in a sec.

**Comment by popey456963** [comment]
Our default karma is kept at 100, however, in our testing, two of our players had karma between 500-600.  I understand the use of punishing lower-karma players, but we don't place a limit on the amount of karma our players can get (it's sort of our player "scoring" system).  I need to go for a couple of hours, but when I get back I'll try setting two of our karmas back to 100 and see whether or not that fixes things.

**Comment by good-live** [comment]
Im just goign to remove that part, as nobody really needs it and it's hardcoded for a default karma of 1000.

**Comment by popey456963** [comment]
Credits earnt is still affected by karma for some unknown reason.

I've updated to 2.1.B152081980, which I think is the latest version, and when I set a players karma to 99,999 they appear to get roughly 12 million credits a round.

**Comment by good-live** [comment]
u need version 153771528 or higher

**Comment by popey456963** [comment]
Ah, I see.

So, on csgottt.com, is the top version not always the latest version?

**Comment by good-live** [comment]
For me are they on the top. However u can always click on the commit to see it in a timeline.

**Comment by popey456963** [comment]
Ah, :+1:!  Don't know what's up with my computer, seems to order them funnily.  Works now that I've upgraded.
