### ISSUE TITLE
Taser Damage Does not work

### ISSUE THREAD

**Issue by Chickenw** [Bara20/TroubleinTerroristTown#46]
So in the config it gives you the option to make it so Tasers can do damage. This option does not work! I do not see errors from it but it just doesnt work i have it set to 100 in config and still does 0 damage just acts as a normal taser

**Comment by good-live** [comment]
If you want the taser to make damage (as normal in csgo) then just remove the ttt_taser. Theres no sense in getting the role of the player, when youre killing him instant.

**Comment by Chickenw** [comment]
Well then it wouldnt work for innos and Det. The way it was reading in the config i thought you could have some roles do damage:P Like T's make them do damage with em

**Comment by Bara20** [comment]
You can modify the damage of tasers for traitors. We've a cvar for innocents/detectives: "ta_damage" and for traitors: "ta_traitor_damage".

**Comment by Bara20** [comment]
I've fixed a bug with taser damage (https://github.com/Bara20/TroubleinTerroristTown/commit/36494ebb02ec501f170ef0fe31d7599bae182d90#diff-9ca4a7dab83323ed4ea09fb1bd309a3cR287). That use the victim role instead attacker role.

**Comment by Bara20** [comment]
Works now (tested on my test server)
