### ISSUE TITLE
Allow Rechoose Detective

### ISSUE THREAD

**Issue by popey456963** [Bara20/TroubleinTerroristTown#47]
Unsurprisingly, my players aren't the brightest in the world.  When confronted with the detective menu, they seem to press random buttons, and then regret their decision.  Could a command, like /detective, be implemented which allows players to reselect whether they have a mic & etc?

**Comment by Bara20** [comment]
https://github.com/Bara20/TroubleinTerroristTown/commit/dd3b0396f419cad2dec8156a9ab0dfa81d049991

I'll add custom commands as cvar later.

**Comment by popey456963** [comment]
Wow, this never got closed.  Apologies.
