### ISSUE TITLE
[request] Implement LogAction on all commands

### ISSUE THREAD

**Issue by iNilo** [Bara20/TroubleinTerroristTown#49]
It would be nice if LogAction could be implemented on all possible admin commands.

https://sm.alliedmods.net/new-api/logging/LogAction

iNilo.

**Comment by Bara20** [comment]
It's possible but necessary? 

Maybe a new function with log,  logtofile and database with a enum for LogType (command,  setrole,...)

**Comment by shanapu** [comment]
To log admin commands I use this: https://forums.alliedmods.net/showthread.php?p=1965353
not the best, but enough for my needs.

**Comment by iNilo** [comment]
I'll see if I can implement it.

But lets take the following example:
Mass deployment of 15 TTT servers.
Central log management.
1 admin abuses, central management has no idea what/how/when.
