### ISSUE TITLE
Reduce high cpu usage (with more players)

### ISSUE THREAD

**Issue by Bara20** [Bara20/TroubleinTerroristTown#5]

**Comment by kikoplg** [comment]
Issue #34

**Comment by popey456963** [comment]
Any particular features that have high CPU usage?

**Comment by Bara20** [comment]
glow-Features (Glow, Wallhack and TA-Grenade) need more cpu usage.

**Comment by good-live** [comment]
Ive edited the glow a few days ago. I think it shouldnt be so cpu intensive now. However it should get tested and then maybe ported to Wallhack and TA-Grenade aswell.

**Comment by popey456963** [comment]
Could we offset the timers that run every 1, 3 and 5 seconds?  At the moment they appear to all run simultaneously, which means every 15 seconds I get slightly increased CPU usage.  Although this would reduce the footprint of the TTT plugin, this would make the usage be spread over a larger amount of time.
