### ISSUE TITLE
Execution Time Out.

### ISSUE THREAD

**Issue by good-live** [Bara20/TroubleinTerroristTown#56]
This next error is a major issue that on roundstart when the plugin selects a T/detective, the server stopps for 20 seconds as if its crashing then starts the game normally. 
L 08/23/2016 - 20:27:46: [SM] Exception reported: Script execution timed out
L 08/23/2016 - 20:27:46: [SM] Blaming: ttt_taser.smx()
L 08/23/2016 - 20:27:46: [SM] Call stack trace:
L 08/23/2016 - 20:27:46: [SM] [1] Line 375, /home/travis/build/Bara20/TroubleinTerroristTown/addons/sourcemod/scripting/include/ttt.inc::HasWeapon()
L 08/23/2016 - 20:27:46: [SM] [2] Line 133, addons/sourcemod/scripting/ttt/ttt_taser.sp::TTT_OnClientGetRole()
L 08/23/2016 - 20:27:46: [SM] [4] Call_Finish
L 08/23/2016 - 20:27:46: [SM] [5] Line 952, addons/sourcemod/scripting/ttt/ttt.sp::TeamInitialize()
L 08/23/2016 - 20:27:46: [SM] [6] Line 849, addons/sourcemod/scripting/ttt/ttt.sp::Timer_Selection()

See #39

**Comment by Bara20** [comment]
Should be fixed with https://github.com/Bara20/TroubleinTerroristTown/commit/9db7dcc0ef44d4944d5248b6ce75d081925ac089
