### ISSUE TITLE
Log file isn't created

### ISSUE THREAD

**Issue by good-live** [Bara20/TroubleinTerroristTown#57]
L 08/23/2016 - 20:53:28: [SM] Exception reported: Could not open file "/servers/giclanttt/csgo/addons/sourcemod/logs/ttt/ttt-16-08-23.log"
L 08/23/2016 - 20:53:28: [SM] Blaming: ttt.smx()
L 08/23/2016 - 20:53:28: [SM] Call stack trace:
L 08/23/2016 - 20:53:28: [SM] [0] LogToFileEx
L 08/23/2016 - 20:53:28: [SM] [1] Line 321, addons/sourcemod/scripting/ttt/ttt.sp::ShowLogs()
L 08/23/2016 - 20:53:28: [SM] [2] Line 589, addons/sourcemod/scripting/ttt/ttt.sp::Event_RoundEndPre()
L 08/23/2016 - 20:53:28: [SM] [4] CS_TerminateRound
L 08/23/2016 - 20:53:28: [SM] [5] Line 2702, addons/sourcemod/scripting/ttt/ttt.sp::CheckTeams()
L 08/23/2016 - 20:53:28: [SM] [6] Line 1796, addons/sourcemod/scripting/ttt/ttt.sp::Event_PlayerDeath()

See #39

**Comment by good-live** [comment]
At least i assume, that it's not created maybe @Chevalier could take a look, whether it's there or not.

**Comment by iNilo** [comment]
Permission issue ?

**Comment by Bara20** [comment]
Check the permissions of ttt logs folder (addons/sourcemod/logs/ttt).

**Comment by good-live** [comment]
Closing since there's no information.
