### ISSUE TITLE
Taser Issues

### ISSUE THREAD

**Issue by Chevalier2016** [Bara20/TroubleinTerroristTown#58]
Latest commit https://github.com/Bara20/TroubleinTerroristTown/commit/08c0a666e23b9f17217c6a647f9a800330da0b2d

L 08/24/2016 - 18:14:19: [SM] Exception reported: Entity -1 (-1) is invalid
L 08/24/2016 - 18:14:19: [SM] Blaming: ttt_taser.smx()
L 08/24/2016 - 18:14:19: [SM] Call stack trace:
L 08/24/2016 - 18:14:19: [SM]   [0] GetEntPropString
L 08/24/2016 - 18:14:19: [SM]   [1] Line 748, /home/travis/build/Bara20/TroubleinTerroristTown/addons/sourcemod/scripting/include/entity.inc::GetEntityClassname()
L 08/24/2016 - 18:14:19: [SM]   [2] Line 169, addons/sourcemod/scripting/ttt/ttt_taser.sp::OnWeaponDrop()

L 08/24/2016 - 18:14:19: [SM] Exception reported: Entity -1 (-1) is invalid
L 08/24/2016 - 18:14:19: [SM] Blaming: ttt_taser.smx()
L 08/24/2016 - 18:14:19: [SM] Call stack trace:
L 08/24/2016 - 18:14:19: [SM]   [0] GetEntPropString
L 08/24/2016 - 18:14:19: [SM]   [1] Line 748, /home/travis/build/Bara20/TroubleinTerroristTown/addons/sourcemod/scripting/include/entity.inc::GetEntityClassname()
L 08/24/2016 - 18:14:19: [SM]   [2] Line 169, addons/sourcemod/scripting/ttt/ttt_taser.sp::OnWeaponDrop()
L 08/24/2016 - 18:14:19: [SM]   [4] ForcePlayerSuicide
L 08/24/2016 - 18:14:19: [SM]   [5] Line 37, playercommands/slay.sp::PerformSlay()
L 08/24/2016 - 18:14:19: [SM]   [6] Line 147, playercommands/slay.sp::Command_Slay()

**Comment by popey456963** [comment]
Exactly the same thing here,

```
L 08/25/2016 - 17:36:13: [SM] Exception reported: Entity -1 (-1) is invalid
L 08/25/2016 - 17:36:13: [SM] Blaming: ttt/ttt_taser.smx()
L 08/25/2016 - 17:36:13: [SM] Call stack trace:
L 08/25/2016 - 17:36:13: [SM]   [0] GetEntPropString
L 08/25/2016 - 17:36:13: [SM]   [1] Line 748, /home/travis/build/Bara20/TroubleinTerroristTown/addons/sourcemod/scripting/include/entity.inc::GetEntityClassname()
L 08/25/2016 - 17:36:13: [SM]   [2] Line 169, addons/sourcemod/scripting/ttt/ttt_taser.sp::OnWeaponDrop()
L 08/25/2016 - 17:36:15: [SM] Exception reported: Entity -1 (-1) is invalid
L 08/25/2016 - 17:36:15: [SM] Blaming: ttt/ttt_taser.smx()
L 08/25/2016 - 17:36:15: [SM] Call stack trace:
L 08/25/2016 - 17:36:15: [SM]   [0] GetEntPropString
L 08/25/2016 - 17:36:15: [SM]   [1] Line 748, /home/travis/build/Bara20/TroubleinTerroristTown/addons/sourcemod/scripting/include/entity.inc::GetEntityClassname()
L 08/25/2016 - 17:36:15: [SM]   [2] Line 169, addons/sourcemod/scripting/ttt/ttt_taser.sp::OnWeaponDrop()
```
Seems to break the plugin so that tasers kill people again.

**Comment by popey456963** [comment]
As a temporary fix, if you change the taser to only show to the individual instead of everyone (in taser.cfg), all these issues seem to go away and the taser functions correctly again.

**Comment by good-live** [comment]
Is this still a problem or was it just not closed?

**Comment by popey456963** [comment]
Watched my console for the past, four-ish hours?  Not getting a single error since I've updated.  Especially some of your recent commits seem amazing in cleaning the TTT plugin up and fixing a bunch of the fixes.  Thanks for your work :+1:.
