### ISSUE TITLE
[Bug] Zeus kills on round end

### ISSUE THREAD

**Issue by popey456963** [Bara20/TroubleinTerroristTown#61]
Apparently the event to reduce damage to 0 on the Zeus fails if the round has ended.

This leads to people often killing each other accidentally.

**Comment by Bara20** [comment]
Set ttt_end_round_dm to 0 and use latest commit (https://github.com/Bara20/TroubleinTerroristTown/commit/baba9302ef9e2050f0a19b963c35b6e09ae1ef18)

**Comment by popey456963** [comment]
:+1:  Thanks for the fix!
