### ISSUE TITLE
[Fix] Healthshot heals extra health

### ISSUE THREAD

**Issue by popey456963** [Bara20/TroubleinTerroristTown#62]
When someone like a detective has 150hp, gets hurt down to say, 90hp and takes a health shot, it still only heals up to 100hp.  Any way to fix it?

**Comment by Bara20** [comment]
Max Health is 100hp, so why you need 150hp? Example?

**Comment by popey456963** [comment]
People hate being the detective on our server, to try to encourage it we allow them to have 150hp in order to be able to take an awp shot to the body, or an ak shot to the head.

**Comment by Yeradon** [comment]
The health shot is a normal item. So you can easily adjust its behaviour using a extra plugin.
