### ISSUE TITLE
!id spam

### ISSUE THREAD

**Issue by Chickenw** [Bara20/TroubleinTerroristTown#64]
Should really add in a sleep timer on the !id.
People can get annoying with spaming !id !id !id like 10 times in a row lol

**Comment by good-live** [comment]
Isn't there a spam protection build in sourcemod?

**Comment by Chickenw** [comment]
Yes but it seems to be for console commands not chat spam

**Comment by popey456963** [comment]
Spam protection for the chat is currently at about two a second for commands?  For something like /id that is far too much.

**Comment by good-live** [comment]
KK goign to make a simpel cooldown. However i still don't get the sense of this plugin ^^

**Comment by good-live** [comment]
@Bara20 you need to update the translation ^^

**Comment by Chickenw** [comment]
Hehe this is why 
[TTT] =|gG|= ChickenWings is Innocent
 [TTT] =|gG|= ChickenWings is Innocent
 [TTT] =|gG|= ChickenWings is Innocent
 [TTT] =|gG|= ChickenWings is Innocent
 [TTT] =|gG|= ChickenWings is Innocent
 [TTT] =|gG|= ChickenWings is Innocent
 [TTT] =|gG|= ChickenWings is Innocent
 [TTT] =|gG|= ChickenWings is Innocent
 [TTT] =|gG|= ChickenWings is Innocent
 [TTT] =|gG|= ChickenWings is Innocent
 [TTT] =|gG|= ChickenWings is Innocent
 [TTT] ✪PROgamer✪ (kickback.com) has found the body of FlAshInG Gunner. That was a INNOCENT!
 [TTT] =|gG|= ChickenWings is Innocent
 [TTT] =|gG|= ChickenWings is Innocent
 [TTT] =|gG|= ChickenWings is Innocent
 [TTT] =|gG|= ChickenWings is Innocent
 [TTT] =|gG|= ChickenWings is Innocent
 [TTT] =|gG|= ChickenWings is Innocent
 [TTT] =|gG|= ChickenWings is Innocent
 [TTT] =|gG|= ChickenWings is Innocent
 [TTT] =|gG|= ChickenWings is Innocent
 [TTT] =|gG|= ChickenWings is Innocent
 [TTT] =|gG|= ChickenWings is Innocent
 [TTT] =|gG|= ChickenWings is Innocent
 [TTT] =|gG|= ChickenWings is Innocent
 [TTT] =|gG|= ChickenWings is Innocent
 [TTT] =|gG|= ChickenWings is Innocent
 [TTT] =|gG|= ChickenWings is Innocent
 [TTT] =|gG|= ChickenWings is Innocent
 [TTT] =|gG|= ChickenWings is Innocent

**Comment by Bara20** [comment]
Done.
