### ISSUE TITLE
Limit of some things not Resetting

### ISSUE THREAD

**Issue by Chickenw** [Bara20/TroubleinTerroristTown#65]
So the limit of Tasers and others are not resetting Each round. Round restarts and still can not buy a Taser. Or when its saying round does it mean Map? Once the map changes i can buy em again.
 [TTT] You've reached the limit for tasers! (Usage(s) per round: 10)

**Comment by Bara20** [comment]
As traitor?

**Comment by Chickenw** [comment]
Yes as a T also its not just for round it follows on map changes too. Don't seem to have this problem as an inno But gonna double check that

**Comment by Bara20** [comment]
https://github.com/Bara20/TroubleinTerroristTown/commit/44dea187f4aeca58e40c00814ca8def157a13ee6

**Comment by Chickenw** [comment]
Thanks will try this

**Comment by Chickenw** [comment]
Working fine now:D

**Comment by popey456963** [comment]
If it's working, you should close the issue so it no longer appears as a problem!

**Comment by Chickenw** [comment]
Had no clue i could do that haha
