### ISSUE TITLE
SM_TVoice Doesn't Work.

### ISSUE THREAD

**Issue by popey456963** [Bara20/TroubleinTerroristTown#66]
It appears to be registered, but doesn't do anything.  I do have both ttt.smx and ttt_talk_override.smx

**Comment by good-live** [comment]
Which version do you have?

**Comment by popey456963** [comment]
2.1.154844348

Like, 3 weeks out of date I think, but none of the latest commits seem to have any relevance to voice.

**Comment by good-live** [comment]
Just didn't loaded the Translation 21471635f2342214d0aceef80fdbe3bada1aff4d

**Comment by kikoplg** [comment]
tested
