### ISSUE TITLE
Everyone declining detective means one person gets it permanently.

### ISSUE THREAD

**Issue by popey456963** [Bara20/TroubleinTerroristTown#67]
TTT V.2.1.154844348

Would be nice if it was randomized if no-one selects yes.  Other options include:

 - Random detectives always (would be nice).
 - More incentives to be detective (such as only choose from people who would be innocents, keep same chance of getting traitor).

We played on five different maps, same person got it over all 120-ish rounds, despite the server being populated with 25-30 people (so humorous for everyone else, less so for the guy that never got traitor).

**Comment by good-live** [comment]
Can you try it with this commit?

**Comment by Chickenw** [comment]
If you are having this problem disable the Det menu. People will always hit buttons and not care thats how it gets bugged. For me its easier just to leave all those rule menus off.

**Comment by popey456963** [comment]
How did you go around disabling it Chickenw?  I can disable it via the config, so it doesn't display automatically, but people can still go about disabling it via /drules.  I would have to edit the source to stop that, and I somewhat like keeping up with the master branch.

**Comment by Chickenw** [comment]
Well.. Just now seen that command I went into the .sp and removed both
	RegConsoleCmd("sm_trules", Command_TRules);
	RegConsoleCmd("sm_drules", Command_DetectiveRules);
I think these commands should just be removed to be honest i dont see a need for them.

**Comment by good-live** [comment]
Those commands bot added in request by him #47
Would you mind to test it with the new Version? T/D should get forced randomly now.

**Comment by popey456963** [comment]
Yeah, have a /drules is still incredibly useful when players aren't the brightest, it's a great step up from being forced to type `retry` in console.  I've tested the new version, and as far as I can see it's working!  That, or 50% of our community has started answering "yes" to the detective part.

Unless I get any further information,  I'm closing this issue!

**Comment by Bara20** [comment]
I've added the necessary checks. https://github.com/Bara20/TroubleinTerroristTown/commit/e15e7b28531f28d4e452c09bd29e5001c36337b7
