### ISSUE TITLE
Buymenu

### ISSUE THREAD

**Issue by kikoplg** [Bara20/TroubleinTerroristTown#69]
Beim kaufen von allen Items kommt keine Rückmeldung im Chat.
Eigentlich sollte iwas kommen von "Item X gekauft. restliche Credits Y" (siehe Translation)
Es kommt allgemein keine Rückmeldung im Chat wenn man etwas kauft.

**Comment by kikoplg** [comment]
* Bei C4 und Jihad kommt eine Message!

**Comment by Bara20** [comment]
https://github.com/Bara20/TroubleinTerroristTown/blob/98777aa080421439acaf91fe08f2a0fb0e9648f3/addons/sourcemod/scripting/ttt/ttt_shop.sp#L250 sollte eigentlich gehen. Gibt es error-Logs?

**Comment by popey456963** [comment]
Same here, getting messages.  Would however be nice to log amount of credits the player has left as @kikoplg said :simple_smile:

**Comment by good-live** [comment]
Might be any Plugin, which is returning always Plugin_Stop in the callback? Havent checked that yet.

**Comment by kikoplg** [comment]
Done - thanks
