### ISSUE TITLE
Grabber mod not working for old players

### ISSUE THREAD

**Issue by kaeming** [Bara20/TroubleinTerroristTown#74]
Some of the players are unable to identify players whether they are innocent or traitor when the person is dead. They also can't grab onto props unlike previously after the updates.

Only new players are able to use the +use function , which is the grabber mod unlike the old players. Any fixes to this?

There is only 1place the grabber mod will work is in ttt_mcdonald below the cashier, which isnt a prop nor any other thing. 

NOTE: only affect old players which played TTT before ( before update )

Tried: 
-other versions

**Comment by good-live** [comment]
There is absoloutly no condition that has something to do with smth. that is saved to a database or any file (Which would make it possible to distinguish between old and new players) in the grabbermod. For me it seems like a thirdparty problem.

**Comment by good-live** [comment]
Closed, because there was no answer.
