### ISSUE TITLE
Latest update means locations show up over voice chat.

### ISSUE THREAD

**Issue by popey456963** [Bara20/TroubleinTerroristTown#75]
An example with the Ts:

![](https://puu.sh/rAWvD/bac6445261.png)

Latest CS:GO update also seemed to break a bunch of other stuff, so unfortunately you might see more issues coming from me in the coming days D:

**Comment by kikoplg** [comment]
Map ?

**Comment by popey456963** [comment]
The map is ttt_community_pool_csgoport_v6

Feel free to download it from http://popey.azureedge.net/csgo/maps/

Apologies if it is a map problem rather than a plugin problem :)

**Comment by kikoplg** [comment]
just rename it ...

**Comment by popey456963** [comment]
What do you mean?  Does renaming the map remove the location names?

**Comment by kikoplg** [comment]
yep

**Comment by popey456963** [comment]
Wow, that's really neat.  Thanks for the tip!  Guess I'll close this.

Enjoy :)

**Comment by popey456963** [comment]
I just suck at closing issues it appears...

**Comment by kikoplg** [comment]
Cant use any of your Maps.

**Comment by popey456963** [comment]
90% of those maps are horrendous and haven't been tested yet, so, likely you're just using a map that hasn't been tested yet and isn't working.

You can see all the maps that we've tested and included by looking at the ones that are "included", on this map:

http://maps.sinisterheavens.com/maplist.php
