### ISSUE TITLE
Troubles with new update SM 1.8

### ISSUE THREAD

**Issue by Ryumov** [Bara20/TroubleinTerroristTown#76]
After updating sourcemode 1.8 to 5942 I have encountered problem. TTT supposed to hide kills in HUD (as it gives info about killer and killed person), but it doesn't. Can you advise me anything please?

**Comment by Yeradon** [comment]
Which version did you updated from? Are there any error logs? Which version of TTT do you use?

**Comment by Ryumov** [comment]
Cant tell which ver was before. Tried on sourcemode 1.8 (TTT ver 367, 376) and sm 1.9 (TTT ver 376) from http://csgottt.com

**Comment by nguyenbaodanh** [comment]
SAme here ! 
using latest sourcemod version

**Comment by Bara20** [comment]
This bug is fixed in latest dev versions.
