### ISSUE TITLE
Addons for TTT

### ISSUE THREAD

**Issue by popey456963** [Bara20/TroubleinTerroristTown#77]
Hello,

Previously there were a bunch of useful plugins on git.tf, hosted under Zipcore, I believe.  This site seems to have gone down recently and this seems a huge loss for TTT.  Are there addons still available somewhere?

I'm talking about plugins such as the weapon spawner & etc.

**Comment by kikoplg** [comment]
I think the Weaponspawner needs a rewrite. 
I only have the pluginfiles wtihout any sp's. 

There are some weaponspawner on AM. But none of them with a randomfunction.

Maybe request a randomfuction for this plugin?

https://forums.alliedmods.net/showthread.php?p=1786838

**Comment by popey456963** [comment]
Don't suppose there's any chance of you uploading your compiled .smx files?  I have a decompiler to verify they are what they seem and it would be insanely useful.

**Comment by good-live** [comment]
Sharing sourcemod binarys without sourcecode is not allowed.

**Comment by popey456963** [comment]
Ah, that's a fair point.  Zipcore was also really helpful and pointed me over to [Gitlab](https://gitlab.com/Zipcore) anyway so I'll close this issue.
