### ISSUE TITLE
Errors with Latest Steam Version

### ISSUE THREAD

**Issue by popey456963** [Bara20/TroubleinTerroristTown#79]
Numerous interesting issues with the latest version.  The main ones being:

 - Universally decreased FPS for all users
 - A strange "ghostlike" figure that displays on all the maps.  Looking at it reduces the FPS to 1:
![](https://puu.sh/rXKkE/49d303ffa3.png)
![](https://puu.sh/rWpdr/55c6b1b580.png)
![](https://puu.sh/rXKol/03bc9d5cbe.png)
 - CClientRenderablesList being overflowed, errors being displayed in the top-right.
![](https://puu.sh/rWpor/977bf63a87.png)
 - Some interesting (hillarious) gun issues that sometimes cause the client to crash:
![](http://image.prntscr.com/image/a9285cebcee24fb7832070713819e510.png)
![](http://images.akamai.steamusercontent.com/ugc/396707750014976066/1227FB8B72DEB19D5C7C900BF36E40E5767C3C2C/?interpolation=lanczos-none&output-format=jpeg&output-quality=95&fit=inside|1024:576&composite-to%3D%2A%2C%2A%7C1024%3A576&background-color=black)

These happen on all maps, since the update from yesterday.

**Comment by shanapu** [comment]
this was discussed here: https://forums.alliedmods.net/showthread.php?t=289648

and fixed with latest commit: https://github.com/Bara20/TroubleinTerroristTown/commit/76e2021715b88f4e8f2713995850a7fa2014d382

**Comment by popey456963** [comment]
Oooh, behind the curve, we were using the dev version from like, 4 hours ago :+1:.

**Comment by good-live** [comment]
So you have the error with the latest dev Version?
Try to disable the Halloween mode manually.

**Comment by popey456963** [comment]
No, sorry, didn't mean that at all.  I thought we were using the latest dev build because I updated it just a few hours ago.  Didn't realise you guys were that amazing and had already released a dev build with a fix.  :+1:
