### ISSUE TITLE
Taser Broadcast Message

### ISSUE THREAD

**Issue by popey456963** [Bara20/TroubleinTerroristTown#80]
Hello,

Quite possibly doing something wrong, we're trying to merge our server back with the latest development version of TTT.  We seem to be getting some interesting translation issues.  The default:

```
    "You tased a Traitor"
    {
        "#format"   "{1:N},{2:N}"
        "en"        "Player {lightgreen}{1} used a detector on Player {darkred}{2} {lightgreen}and he is a {darkred}TRAITOR!"
    }
```

Brings up an error that when you call it you're missing one parameter.  Thus we've recently made the alteration to:

```
    "You tased a Traitor"
    {
        "#format"   "{1:N}"
        "en"        "{darkred}{1}{lightgreen} was tased and is a {darkred}TRAITOR!"
    }
```

Which works, but doesn't tell us who the person was that tased the guy.  Which isn't optimal.  Are we either:
1. Doing something wrong.
2. The default translation is wrong.
3. The call to the translation is wrong.

Preferably, it would be nice to include the person that did the tasing.  We currently have tasing so it is broadcast to all.

**Comment by good-live** [comment]
3 is wrong however i can't fix it right now. Feel free to do it yourself.

**Comment by popey456963** [comment]
Will look into it!

**Comment by Bara20** [comment]
I see no fail on line https://github.com/Bara20/TroubleinTerroristTown/blob/master/addons/sourcemod/scripting/ttt/ttt_taser.sp#L261 or in thr translation file. 

Maybe outdated translation?

**Comment by popey456963** [comment]
Nope @Bara20.  Updated yesterday to conform with the current translation file:

```
	"You tased a Traitor"
	{
		"#format"	"{1:N},{2:N}"
		"en"		"Player {lightgreen}{1} used a detector on Player {darkred}{2} {lightgreen}and he is a {darkred}TRAITOR!"
	}
```

Doesn't work because it doesn't seem to provide two parameters, only one.

**Comment by good-live** [comment]
@Bara there is only one translation Parameter passend. The first one is to indicate the client language, but the Translation needs 2 parameters

**Comment by good-live** [comment]
I found some time to fix it, but i have no chance to test it. @popey456963 that's your part.

**Comment by popey456963** [comment]
We're doing our bi-weekly update of TTT on Saturday, will test it then @good-live .

Thanks!

**Comment by Bara20** [comment]
@good-live loop clients and use client index instead of LANG_SERVER (english for german (or russian) players?

**Comment by popey456963** [comment]
@Bara20 Is that the reason that sometimes messages appear in German to everyone?  Despite me wanting English?

**Comment by Bara20** [comment]
I don't know. What is value of "ServerLang" in your core.cfg ( https://github.com/alliedmodders/sourcemod/blob/master/configs/core.cfg#L30 )?

**Comment by good-live** [comment]
@Bara20 would be cleaner yeah :)

@popey456963 Nope with the current setup it would be always the Server language.

**Comment by popey456963** [comment]
@Bara20 @good-live `"ServerLang"    "en"`

Which is humorous because sometimes it does definitely display in a non-English language.  I removed all other translations to force it to English and it worked.  Feel like this is a bug with Sourcemod/Our server and not you though now, as it does sometimes happen to other plugins as well.

**Comment by good-live** [comment]
Have you already updates? Before my commit it has taken the attackers language.

**Comment by popey456963** [comment]
Wait, no, sorry to confuse.  This was from ages ago.  I need to wait till Saturday to try your latest commit.  @good-live

**Comment by popey456963** [comment]
Tested for a few days, appears to be fixed!

Thanks guys.
