### ISSUE TITLE
Menu

### ISSUE THREAD

**Issue by kikoplg** [Bara20/TroubleinTerroristTown#81]
Beim Kauf im Menu soll sich das Menu nicht immer automatisch schliessen, falls man mehr als nur 1 Item kaufen will. Das Menu soll so lange offen bleiben bis man es mit dem "exit"-Button schliesst.

**Comment by good-live** [comment]
Ich hab das ganze mal testweise Eingebaut #untested 👍 @kikoplg bitte testen.
818bc47670bc033ac97a992ec6649d6de91262d5

**Comment by Bara20** [comment]
Warum sollte es nicht gehen? Würde es allerdings eher nur beim erfolgreichen Kauf neu öffnen oder man baut ein 2. Check ein, was es beim erfolglosen auch neu öffnet.

**Comment by good-live** [comment]
Man kann immer irgendetwas übersehen ^^ Wegen mir kann man das Menü auch nur beim erfolgreichen Kauf erneut öffnen. @kikoplg Was sagst du dazu?

**Comment by kikoplg** [comment]
Wenn das Item zu teuer ist, sollte sich das Menu trotzdem neu öffnen.

**Comment by shanapu** [comment]
meine empfehlung. macht ein cvar ob das menu neu geöffnet werden soll oder nicht.
Hatte in myjb zuerst 'auto-reopen' da kammen die ersten und wünschten sich dass es sich automatisch schliessen soll. Gesagt, getan. Nächste 'beschwerde' - warum es sich nicht mehr öffnet.
Cvar = alle Glücklich

**Comment by kikoplg** [comment]
funktioniert! Vielen Dank

**Comment by good-live** [comment]
Players wished to have a cookie for this. So they can decide themself to use it or not.
