### ISSUE TITLE
Buy Commands

### ISSUE THREAD

**Issue by popey456963** [Bara20/TroubleinTerroristTown#82]
It would be nice to have a command like:

    !buyitem <name>

So that people could bind purchases such as `bind f8 "sm_buyitem taser"`.  It's got very positive responses from members of my community.

**Comment by good-live** [comment]
Goign to take a look at it, when i habe some time. Should be easy to do.

**Comment by Bara20** [comment]
So we can use the short names for this or a new string like "nameForCommand" ?

**Comment by good-live** [comment]
I would use the short names and add a command to show the users the relation between short and long name.

**Comment by Bara20** [comment]
Closed, if anyone has problems write it here or create a new issue.
