### ISSUE TITLE
Need help with map

### ISSUE THREAD

**Issue by ZweGGy** [Bara20/TroubleinTerroristTown#86]
**Map just doesn't download** from the server... When I start normal mapt (ets: Nuke...) It starts, but any TTT custom map doesn't ! Pleaze help :)

**Comment by good-live** [comment]
This has nothing to do with the TTT Plugin. You should ask for some help in a CS:GO related forum.

**Comment by ZweGGy** [comment]
It is..

**Comment by whocodes** [comment]
The plugin has nothing to do with maps made by independent map makers, or your server issues loading the maps.


On Nov 25, 2016, at 10:30 AM, ZweGGy <notifications@github.com<mailto:notifications@github.com>> wrote:


It is..

-
