### ISSUE TITLE
Interface Name

### ISSUE THREAD

**Issue by Cr4fter** [Bara20/TroubleinTerroristTown#87]
The interface telling the name and karma of players shows the name of traitors in blue. So everybody can see who is traitor.
Only tested width 3 players.

**Comment by good-live** [comment]
You can set the color in the translation.

**Comment by Cr4fter** [comment]
OK found the mistake. In the default German translation.
"﻿Hud﻿ PlayerName I-T"
{
"de" "'#0000ff'&gt;\"{1}\"font&gt;"
}
needs to be:
"Hud PlayerName I-T"
{
"de" "\"{1}\"font&gt;"
}
Thanks fro the help :)
