### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Demono5060** [Bara20/TroubleinTerroristTown#88]
https://www.youtube.com/watch?v=jPtDQlheUGQ

**Comment by whocodes** [comment]
Perhaps a prop thats not actually a static immovable prop, but instead anchored or attached to a prop that is?

On Jan 24, 2017, at 6:19 AM, Demono5060 <notifications@github.com<mailto:notifications@github.com>> wrote:


https://www.youtube.com/watch?v=jPtDQlheUGQ

-

**Comment by good-live** [comment]
Test

 

Von: Cameron Smith [mailto:notifications@github.com] 
Gesendet: Dienstag, 24. Januar 2017 12:48
An: Bara20/TroubleinTerroristTown <TroubleinTerroristTown@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: Re: [Bara20/TroubleinTerroristTown] Bug (#88)

 

Perhaps a prop thats not actually a static immovable prop, but instead anchored or attached to a prop that is?

On Jan 24, 2017, at 6:19 AM, Demono5060 <notifications@github.com <mailto:notifications@github.com%3cmailto:notifications@github.com> <mailto:notifications@github.com>> wrote:


https://www.youtube.com/watch?v=jPtDQlheUGQ

-

**Comment by Aura89** [comment]
On our server we have a plugin created by the community that prevents being able to press "e" on many unmovable objects (that were launching everyone when someone would try and move it, such as cars). I wish TTT would implement this officially. As far as i understand it, the way it's currently being fixed is by making it so people can't jump on those objects. Problem is, this makes it impossible to get to many ledges on many maps.

**Comment by Bara20** [comment]
`we have a plugin created by the community`
And you could share this with us.

**Comment by Aura89** [comment]
i only have the smx file, not the sp file, and it's an edited form of the grabbermod. I'm not sure what was edited, and it won't let me upload it here. I can send it to you via discord if you use that.
