### ISSUE TITLE
Enhance show_name.sp and rename to ttt-playerhud.sp

### ISSUE THREAD

**Issue by kikoplg** [Bara20/TroubleinTerroristTown#9]
I think we should enhance the customization of the module.
Display formatting loaded from configuration file and keywords are replaced;

{NAME} - %T for the word Name
{PLAYERNAME} - the player's name
{HEALTH} - %T for the word Health
{PLAYERHEALTH} - %T for the player's Health amount

Allowing for customization. A single forward will be added to modify the content of the character before it is sent.

**Comment by good-live** [comment]
e37321c Could somebody verify, that it is working?

**Comment by kikoplg** [comment]
https://gyazo.com/0d73f5e88a37fce0bdc4dbcc1d88b55a

**Comment by Bara20** [comment]
@good-live ?

**Comment by good-live** [comment]
That's already done.

**Comment by good-live** [comment]
Just need to fix a small bug. Currently it's not displaying informations about unassigned Players.

**Comment by good-live** [comment]
Should work out of the box, but a small test would be nice.

**Comment by Bara20** [comment]
Closed, if anyone has problems write it here or create a new issue.
