### ISSUE TITLE
CSGO Update Feb-03 Bug: Round not ending after all Traitors die

### ISSUE THREAD

**Issue by PresidentEvil** [Bara20/TroubleinTerroristTown#90]
sometimes the round does not end after all Ts are dead

this bug happened after today's update

sm version
SourceMod Version Information:
SourceMod Version: 1.8.0.5969
SourcePawn Engine: SourcePawn 1.8, jit-x86 (build 1.8.0.5969)
SourcePawn API: v1 = 4, v2 = 11
Compiled on: Jan 20 2017 13:16:22
Built from: https://github.com/alliedmodders/sourcemod/commit/f6144a2
Build ID: 5969:f6144a2
http://www.sourcemod.net/

TTT version: 2.1

**Comment by good-live** [comment]
Should be fixed with the latest sourcemod version.
