### ISSUE TITLE
Blue und White ?!

### ISSUE THREAD

**Issue by Famous030** [Bara20/TroubleinTerroristTown#91]
Hello ;).

I installed TTT SourceMod 1.8 with TTT 937 from http://csgottt.com/..

now my Issues ...

When i'm Looking an a player they tell me NAME and KARMA ... 
There are my Issues:

TRAITORS - BLUE Name
Inc. - White 

so i can every Round see who is the  T  ..... 

how can i fix this Issue ?

Thank very mutch

**Comment by shanapu** [comment]
https://github.com/Bara20/TroubleinTerroristTown/issues/87
https://github.com/Bara20/TroubleinTerroristTown/issues/89

> You can set the color in the translation.

**Comment by good-live** [comment]
@Bara20 könntest du einmal die Standard translation anpassen?
