### ISSUE TITLE
Set Karma [[SM] Player data not loaded yet.]

### ISSUE THREAD

**Issue by NicronS** [Bara20/TroubleinTerroristTown#93]
Hey, i'm getting this issue trying to set karma ingame whether is on a sqlite or mysql database

if (g_bKarma[target])
{
    ReplyToCommand(client, "[SM] Player data not loaded yet.");
    return Plugin_Handled;
}

https://imgur.com/a/qlWqX
https://imgur.com/a/khBOL

**Comment by good-live** [comment]
Do you have any errors related to the db query?

**Comment by NicronS** [comment]
http://pastebin.com/b6gPArDA
http://pastebin.com/aLzUt69W

**Comment by Bara20** [comment]
Weird, and database and tables are olay?

**Comment by good-live** [comment]
Have you checked the ttt error log: ttt_error_file

**Comment by NicronS** [comment]
Yes the tables are intact, player data gets, no database errors in In the logs. As for your question good-live ttt seems to nor create its own logs under logs/ttt/

**Comment by NicronS** [comment]
Any idea on this?

**Comment by Bara20** [comment]
Still?

**Comment by NicronS** [comment]
Yes.

**Comment by ShawnCZek** [comment]
Same problem.

**Comment by Bara20** [comment]
#100

**Comment by Bara20** [comment]
Should be fixed with https://github.com/Bara20/TroubleinTerroristTown/commit/9d69d283b3a1f681e54a0ae51217dfae08e581f7

**Comment by NicronS** [comment]
This seems to have fixed our karma issues.
