### ISSUE TITLE
Add hud_text support

### ISSUE THREAD

**Issue by Bara20** [Bara20/TroubleinTerroristTown#94]
Horizontal: http://steamcommunity.com/sharedfiles/filedetails/?id=897939370
Vertical:      http://steamcommunity.com/sharedfiles/filedetails/?id=897934885

**Comment by Bara20** [comment]
Tested and works fine

**Comment by Aura89** [comment]
How do we make ours look like this?

**Comment by Bara20** [comment]
Change ttt_hud_text_enable to true in your overlay config.

**Comment by Aura89** [comment]
Well your warning that it is buggy on 16:9 is definitely warranted. Hopefully there's a way to fix that lol
