### ISSUE TITLE
Not making someone traitor/detective after the round you bought them

### ISSUE THREAD

**Issue by Aura89** [Bara20/TroubleinTerroristTown#96]
I'm using build 975 and whenever people purchase traitor or detective, the next round they are not traitor or detective. It's not because other people have bought it either, as i tested make sure only one person bought traitor or detective, and neither of them became traitor or detective.

**Comment by good-live** [comment]
Thanks for the report.
I'm goign to check that out, when i have some time.

**Comment by Aura89** [comment]
Thanks

**Comment by good-live** [comment]
Are there and error logs?

**Comment by Aura89** [comment]
Where would the error logs be? i do not see any where i believe they would be.

**Comment by Bara20** [comment]
Could you reproduce this with the latest version?

**Comment by Aura89** [comment]
I will try and upgrade our server soon and see if it continues.

**Comment by Bara20** [comment]
Any updates here? Otherwise I'll close it with 2.2..

**Comment by good-live** [comment]
Should be fixed now.
