### ISSUE TITLE
Buy traitor/detective instantly

### ISSUE THREAD

**Issue by Aura89** [Bara20/TroubleinTerroristTown#97]
Is it possible to add an option where instead of buying traitor/detective for next round, it happens instantly? Awhile ago we had a plugin on our server that a community member created that allowed us to buy traitor or detective and immediately became them. 

We made it cost i believe 40000 for traitor and 10000 for detective, but it definitely created an aspect of uncertainty to the game.

I'm not asking to get rid of the option to buy traitor/detective for next round, btw. I'm sure each server would want to use it differently, but just an option in the config file to set it so buying roles happens next round, or instantly.

**Comment by Bara20** [comment]
@Aura89 Open a new issue, if you've problems
