### ISSUE TITLE
Karma (database) error

### ISSUE THREAD

**Issue by Refereee** [Bara20/TroubleinTerroristTown#98]
Hi,
when I join to the game, I have sometimes random karma from other player in database or 0 karma.
When you are ingame and map is changing, you receive your karma correctly.
I'm using MySQL database. I tried sqlite, but I have the same problem.
TTT error log is like:

> L 04/08/2017 - 10:55:27: (LoadClientKarma) Auth failed: #1
> L 04/08/2017 - 11:04:38: (LoadClientKarma) Auth failed: #2
> L 04/08/2017 - 11:11:44: (LoadClientKarma) Auth failed: #2
> L 04/08/2017 - 11:17:24: (LoadClientKarma) Auth failed: #3
> L 04/08/2017 - 11:22:26: (LoadClientKarma) Auth failed: #4
> L 04/08/2017 - 11:23:26: (LoadClientKarma) Auth failed: #5
> L 04/08/2017 - 11:28:26: (LoadClientKarma) Auth failed: #6
> L 04/08/2017 - 11:30:15: (LoadClientKarma) Auth failed: #7
> L 04/08/2017 - 11:46:27: (LoadClientKarma) Auth failed: #7
> L 04/08/2017 - 11:55:58: (LoadClientKarma) Auth failed: #7
> L 04/08/2017 - 12:02:02: (LoadClientKarma) Auth failed: #1
> L 04/08/2017 - 12:10:56: (LoadClientKarma) Auth failed: #8
> L 04/08/2017 - 12:13:42: (LoadClientKarma) Auth failed: #8
> L 04/08/2017 - 12:14:15: (LoadClientKarma) Auth failed: #9
> L 04/08/2017 - 12:14:15: (LoadClientKarma) Auth failed: #11
> L 04/08/2017 - 12:14:37: (LoadClientKarma) Auth failed: #10
> L 04/08/2017 - 12:22:51: (LoadClientKarma) Auth failed: #1
> L 04/08/2017 - 12:25:14: (LoadClientKarma) Auth failed: #7

I'm using last version of TTT (975). Thank you

**Comment by good-live** [comment]
For some reason it isn't able to get the steamID64 from a client.

**Comment by Refereee** [comment]
But after map change it is OK.

**Comment by Bara20** [comment]
@Refereee Could you try build 976 if it available?

**Comment by Refereee** [comment]
So, I tried and here is the result:
When I join to the server, i receive 0 Karma (but I have set karma on start to 500), when I reconnect, I have karma before disconnect. But, when I restart the server, my Karma is on 0 again, did not save.

**Comment by Bobakanoosh** [comment]
I just update my server to the latest. Having the same issue. I manually added myself to the database and everything updates/saves fine. The issue is that players aren't automatically added on join or w/e.

**Comment by Bara20** [comment]
#100
