### ISSUE TITLE
Unable to load TTTTplugin  

### ISSUE THREAD

**Issue by hereww** [Bara20/TroubleinTerroristTown#99]
Help!

----------------------------------------------------------------
sourcemod-1.9.0-git6074-windows
mmsource-1.10.6-windows
ttt-dev-1.9-976-3a13eb5
----------------------------------------------------------------

L 04/11/2017 - 16:30:28: SourceMod error session started
L 04/11/2017 - 16:30:28: Info (map "de_dust") (file "errors_20170411.log")
L 04/11/2017 - 16:30:28: [SM] Exception reported: [TTT] Can't open File: addons\sourcemod\configs\ttt\badnames.ini
L 04/11/2017 - 16:30:28: [SM] Blaming: ttt\ttt.smx
L 04/11/2017 - 16:30:28: [SM] Call stack trace:
L 04/11/2017 - 16:30:28: [SM]   [0] SetFailState
L 04/11/2017 - 16:30:28: [SM]   [1] Line 3240, addons/sourcemod/scripting/ttt/ttt.sp::LoadBadNames
L 04/11/2017 - 16:30:28: [SM]   [2] Line 86, addons/sourcemod/scripting/ttt/ttt.sp::OnPluginStart
L 04/11/2017 - 16:30:28: [SM] Unable to load plugin "ttt\ttt.smx": Error detected in plugin startup (see error logs)
L 04/11/2017 - 16:30:28: [SM] Unable to load plugin "ttt\ttt_api_test.smx": Native "TTT_GetClientKarma" was not found
L 04/11/2017 - 16:30:28: [SM] Unable to load plugin "ttt\ttt_buyRoles.smx": Native "TTT_GetClientRole" was not found
L 04/11/2017 - 16:30:28: [SM] Unable to load plugin "ttt\ttt_c4_jihad.smx": Native "TTT_GetClientRole" was not found
L 04/11/2017 - 16:30:28: [SM] Unable to load plugin "ttt\ttt_decoy_teleport.smx": Native "TTT_GetClientRole" was not found
L 04/11/2017 - 16:30:28: [SM] Unable to load plugin "ttt\ttt_dnascanner.smx": Native "TTT_GetClientRole" was not found
L 04/11/2017 - 16:30:28: [SM] Unable to load plugin "ttt\ttt_fakebody.smx": Native "TTT_SetRagdoll" was not found
L 04/11/2017 - 16:30:28: [SM] Unable to load plugin "ttt\ttt_glow.smx": Native "TTT_IsRoundActive" was not found
L 04/11/2017 - 16:30:28: [SM] Unable to load plugin "ttt\ttt_healthshot.smx": Native "TTT_GetClientRole" was not found
L 04/11/2017 - 16:30:28: [SM] Unable to load plugin "ttt\ttt_iceknife.smx": Native "TTT_IsRoundActive" was not found
L 04/11/2017 - 16:30:28: [SM] Unable to load plugin "ttt\ttt_icon.smx": Native "TTT_GetClientRole" was not found
L 04/11/2017 - 16:30:29: [SM] Unable to load plugin "ttt\ttt_id.smx": Native "TTT_GetClientRole" was not found
L 04/11/2017 - 16:30:29: [SM] Unable to load plugin "ttt\ttt_overlay.smx": Native "TTT_GetClientRole" was not found
L 04/11/2017 - 16:30:29: [SM] Unable to load plugin "ttt\ttt_playerhud.smx": Native "TTT_GetClientKarma" was not found
L 04/11/2017 - 16:30:29: [SM] Unable to load plugin "ttt\ttt_shop.smx": Native "TTT_GetClientRole" was not found
L 04/11/2017 - 16:30:29: [SM] Unable to load plugin "ttt\ttt_stations.smx": Native "TTT_RegisterCustomItem" was not found
L 04/11/2017 - 16:30:29: [SM] Unable to load plugin "ttt\ttt_tagrenade.smx": Native "TTT_IsRoundActive" was not found
L 04/11/2017 - 16:30:29: [SM] Unable to load plugin "ttt\ttt_talk_override.smx": Native "TTT_IsRoundActive" was not found
L 04/11/2017 - 16:30:29: [SM] Unable to load plugin "ttt\ttt_taser.smx": Native "TTT_RegisterCustomItem" was not found
L 04/11/2017 - 16:30:29: [SM] Unable to load plugin "ttt\ttt_traitordoors.smx": Native "TTT_GetClientRole" was not found
L 04/11/2017 - 16:30:29: [SM] Unable to load plugin "ttt\ttt_wallhack.smx": Native "TTT_RegisterCustomItem" was not found
L 04/11/2017 - 16:30:29: [SM] Unable to load plugin "ttt\ttt_weapons.smx": Native "TTT_RegisterCustomItem" was not found
L 04/11/2017 - 16:30:37: Error log file session closed.

**Comment by good-live** [comment]
Please READ the error:
L 04/11/2017 - 16:30:28: [SM] Exception reported: [TTT] Can't open File: addons\sourcemod\configs\ttt\badnames.ini
